Cargo.toml, js/Cargo.toml
Closes https://github.com/kylebarron/geoarrow-rs/issues/48
=> add geospatial category to crate metadata

Cargo.lock, Cargo.toml, js/Cargo.lock, js/package.json, js/src/algorithm/geo/geodesic_area.rs, js/src/algorithm/geoarrow/coord_format.rs, js/src/algorithm/geoarrow/mod.rs, js/src/algorithm/mod.rs, js/typedoc.json, js/yarn.lock, src/array/binary/array.rs, src/array/coord/combined/array.rs, src/array/coord/interleaved/array.rs, src/array/coord/interleaved/mutable.rs, src/array/coord/mod.rs, src/array/coord/separated/array.rs, src/array/coord/separated/mutable.rs, src/array/geometry/array.rs, src/array/linestring/array.rs, src/array/mod.rs, src/array/multilinestring/array.rs, src/array/multipoint/array.rs, src/array/multipolygon/array.rs, src/array/point/array.rs, src/array/polygon/array.rs, src/trait_.rs
- `coord_type` to get the current coordinate type (interleaved/separated) of this array
- `into_coord_type` to convert this array to a different coordinate type.
- JS bindings for each of these.
Closes https://github.com/kylebarron/geoarrow-rs/issues/44
=> Information on coordinate type

src/array/linestring/array.rs, src/array/point/array.rs, src/scalar/linestring/scalar.rs
=> fix skipped tests

src/array/binary/array.rs, src/array/geometry/array.rs, src/array/linestring/array.rs, src/array/multilinestring/array.rs, src/array/multipoint/array.rs, src/array/multipolygon/array.rs, src/array/polygon/array.rs
Closes https://github.com/kylebarron/geoarrow-rs/issues/88
=> i32-i64 conversions

src/array/binary/array.rs, src/array/geometry/array.rs, src/array/linestring/array.rs, src/array/multilinestring/array.rs, src/array/multipoint/array.rs, src/array/multipolygon/array.rs, src/array/polygon/array.rs
Closes https://github.com/kylebarron/geoarrow-rs/issues/89
=> Implement `From` for arrow2 arrays to either i32 or i64 geometry arrays

src/array/coord/interleaved/array.rs, src/array/coord/separated/array.rs, src/array/linestring/array.rs, src/array/linestring/mutable.rs, src/array/multilinestring/array.rs, src/array/multilinestring/mutable.rs, src/array/multipoint/array.rs, src/array/multipoint/mutable.rs, src/array/multipolygon/array.rs, src/array/multipolygon/mutable.rs, src/array/point/array.rs, src/array/point/mutable.rs, src/array/polygon/array.rs, src/array/polygon/mutable.rs, src/scalar/point/owned.rs
Validate that offsets and validity have the correct length
=> Implement initialization checks

src/algorithm/geo/line_interpolate_point.rs, src/algorithm/geo/line_locate_point.rs, src/algorithm/geo/minimum_rotated_rect.rs, src/algorithm/geo/mod.rs, src/algorithm/geo/remove_repeated_points.rs, src/algorithm/geo/within.rs, src/array/point/mutable.rs
Wrap
- `LineInterpolatePoint`
- `LineLocatePoint`
- `MinimumRotatedRect`
- `RemoveRepeatedPoints`
- `Within`
=> More algorithms

src/io/geozero/array/linestring.rs, src/io/geozero/array/multilinestring.rs, src/io/geozero/array/multipoint.rs, src/io/geozero/array/multipolygon.rs, src/io/geozero/array/point.rs, src/io/geozero/array/polygon.rs, src/io/geozero/mod.rs, src/io/geozero/scalar/linestring.rs, src/io/geozero/scalar/mod.rs, src/io/geozero/scalar/multilinestring.rs, src/io/geozero/scalar/multipoint.rs, src/io/geozero/scalar/multipolygon.rs, src/io/geozero/scalar/point.rs, src/io/geozero/scalar/polygon.rs, src/scalar/linestring/scalar.rs, src/scalar/multilinestring/scalar.rs, src/scalar/multipoint/scalar.rs, src/scalar/multipolygon/scalar.rs, src/scalar/polygon/scalar.rs
Allows converting from arrow scalars to geozero outputs
=> implement GeozeroGeometry for Scalars

src/array/binary/array.rs, src/array/coord/combined/array.rs, src/array/coord/interleaved/array.rs, src/array/coord/separated/array.rs, src/array/geometry/array.rs, src/array/geometrycollection/array.rs, src/array/linestring/array.rs, src/array/mixed/array.rs, src/array/multilinestring/array.rs, src/array/multipoint/array.rs, src/array/multipolygon/array.rs, src/array/point/array.rs, src/array/polygon/array.rs, src/array/rect/array.rs, src/trait_.rs, src/util.rs
prep work for `ToOwned` in https://github.com/kylebarron/geoarrow-rs/pull/119
=> Owned slices

src/algorithm/native/bounding_rect.rs, src/algorithm/native/eq.rs, src/array/multipolygon/mutable.rs, src/array/polygon/array.rs, src/array/polygon/mutable.rs, src/geo_traits/polygon.rs, src/io/geos/scalar/polygon.rs, src/io/geozero/scalar/polygon.rs, src/io/native/wkb/polygon.rs, src/scalar/polygon/scalar.rs
Closes https://github.com/kylebarron/geoarrow-rs/issues/83
=> Support empty polygon in polygon trait

src/algorithm/native/eq.rs, src/array/point/array.rs, src/io/native/wkb/point.rs, src/scalar/point/scalar.rs
ref https://github.com/kylebarron/geoarrow-rs/issues/84
=> Allow NaN points to resolve to equal

js/src/lib.rs, js/src/scalar/linestring.rs, js/src/scalar/mod.rs, js/src/scalar/multilinestring.rs, js/src/scalar/multipoint.rs, js/src/scalar/multipolygon.rs, js/src/scalar/point.rs, js/src/scalar/polygon.rs, src/array/point/array.rs, src/scalar/linestring/mod.rs, src/scalar/linestring/owned.rs, src/scalar/linestring/scalar.rs, src/scalar/mod.rs, src/scalar/multilinestring/mod.rs, src/scalar/multilinestring/owned.rs, src/scalar/multilinestring/scalar.rs, src/scalar/multipoint/mod.rs, src/scalar/multipoint/owned.rs, src/scalar/multipoint/scalar.rs, src/scalar/multipolygon/mod.rs, src/scalar/multipolygon/owned.rs, src/scalar/multipolygon/scalar.rs, src/scalar/point/mod.rs, src/scalar/point/owned.rs, src/scalar/point/scalar.rs, src/scalar/polygon/mod.rs, src/scalar/polygon/owned.rs, src/scalar/polygon/scalar.rs
Closes https://github.com/kylebarron/geoarrow-rs/issues/114, closes https://github.com/kylebarron/geoarrow-rs/issues/15
=> Owned scalars and JS scalars

.github/workflows/python-core-wheels.yml
Wheel setup for the `geoarrow.rust` package
Sdist is failing due to https://github.com/PyO3/maturin/issues/1083#issuecomment-1674085413
=> Python core wheels

.github/workflows/python-core-wheels.yml, python/geoarrow-rust/pyproject.toml
Thanks to https://github.com/PyO3/maturin/pull/1728
=> Enable python sdist

js/src/io/parquet.rs, src/io/parquet/reader.rs
Closes https://github.com/kylebarron/geoarrow-rs/issues/159
=> Geoparquet reading takes Read + Seek object

src/array/binary/mutable.rs, src/io/wkb/writer/geometry.rs, src/io/wkb/writer/geometrycollection.rs, src/io/wkb/writer/linestring.rs, src/io/wkb/writer/mod.rs, src/io/wkb/writer/multilinestring.rs, src/io/wkb/writer/multipoint.rs, src/io/wkb/writer/multipolygon.rs, src/io/wkb/writer/point.rs, src/io/wkb/writer/polygon.rs
I think this is the first successful usage of the `GeometryTrait` in action, but using the `GeometryCollectionTrait` fails 😢
=> Write a GeometryTrait instance to wkb

.github/workflows/ci.yml, build/.gitattributes, build/.gitignore, build/pixi.lock, build/pixi.toml
See https://prefix.dev/. This is actually really easy! Looking forward to tryint it for wheels.
=> Use pixi for native dependency management on CI

Cargo.toml, benches/wkb.rs, fixtures/README.md
```
parse WKBArray to geoarrow MultiPolygonArray
time:   [18.268 ms 18.380 ms 18.504 ms]
parse WKBArray to Vec<geo::Geometry>
time:   [42.187 ms 42.365 ms 42.561 ms]
```
=> WKB benchmark

src/algorithm/native/eq.rs, src/array/linestring/array.rs, src/array/multilinestring/array.rs, src/array/multipoint/array.rs, src/array/multipolygon/array.rs, src/array/point/array.rs, src/array/polygon/array.rs, src/scalar/coord/interleaved/scalar.rs, src/scalar/coord/separated/scalar.rs
Follow up on https://github.com/geoarrow/geoarrow-rs/pull/209
=> Restore PartialEq

Cargo.lock, Cargo.toml, src/algorithm/geo/dimensions.rs, src/algorithm/geo/minimum_rotated_rect.rs, src/array/geometrycollection/array.rs, src/array/linestring/array.rs, src/array/multipoint/array.rs
closes https://github.com/geoarrow/geoarrow-rs/issues/219 .
=> Enable doc test

src/array/linestring/iterator.rs, src/array/linestring/mod.rs, src/array/polygon/iterator.rs, src/scalar/linestring/iterator.rs, src/scalar/linestring/mod.rs, src/scalar/linestring/scalar.rs, src/scalar/polygon/iterator.rs, src/scalar/polygon/mod.rs, src/scalar/polygon/scalar.rs
closes https://github.com/geoarrow/geoarrow-rs/issues/210.
=> Move scalar iterators into scalar mod

js/Cargo.lock, js/src/algorithm/geo/bounding_rect.rs, js/src/array/mod.rs, js/src/array/rect.rs, src/algorithm/geo/bounding_rect.rs, src/array/polygon/array.rs, src/array/rect/array.rs
closes https://github.com/geoarrow/geoarrow-rs/issues/231.
=> bounding_rect return RectArray & Impl From<RectArray> for PolygonArray

src/array/coord/combined/mutable.rs, src/array/coord/interleaved/array.rs, src/array/coord/interleaved/mutable.rs, src/array/coord/separated/array.rs, src/array/coord/separated/mutable.rs, src/array/linestring/array.rs, src/array/linestring/mutable.rs, src/array/multilinestring/array.rs, src/array/multilinestring/mutable.rs, src/array/multipoint/array.rs, src/array/multipoint/mutable.rs, src/array/multipolygon/array.rs, src/array/multipolygon/mutable.rs, src/array/point/array.rs, src/array/point/mutable.rs, src/array/polygon/array.rs, src/array/polygon/mutable.rs, src/array/rect/array.rs, src/array/rect/mutable.rs, src/io/geos/array/linestring.rs, src/io/geos/array/multilinestring.rs
=> Use geometry traits in conversion from vector of geoms

.github/workflows/python.yml, python/core/src/array/linestring.rs, python/core/src/array/point.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/268
=> re-enable python ci

Cargo.lock, Cargo.toml, README.md, benches/geos_buffer.rs, benches/nybb.rs, benches/wkb.rs, js/Cargo.lock, js/Cargo.toml, python/core/Cargo.lock, python/core/Cargo.toml, src/algorithm/geo/area.rs, src/algorithm/geo/centroid.rs, src/algorithm/geo/chamberlain_duquette_area.rs, src/algorithm/geo/euclidean_length.rs, src/algorithm/geo/geodesic_area.rs, src/algorithm/geo/geodesic_length.rs, src/algorithm/geo/haversine_length.rs, src/algorithm/geo/line_locate_point.rs, src/algorithm/geo/simplify.rs, src/algorithm/geo/simplify_vw.rs, src/algorithm/geo/vincenty_length.rs, src/trait_.rs
So happy I can do this!
Closes https://github.com/geoarrow/geoarrow-rs/issues/269
=> rename crate to geoarrow

src/array/linestring/builder.rs, src/array/multilinestring/builder.rs, src/array/multipoint/builder.rs, src/array/multipolygon/builder.rs, src/array/offset_builder.rs, src/array/polygon/builder.rs, src/array/rect/builder.rs
This is just a stub to remember to complete after https://github.com/geoarrow/geoarrow-rs/pull/299, since there will be some merge conflicts
=> reserve exact offsets

src/io/geozero/array/linestring.rs, src/io/geozero/array/mod.rs, src/io/geozero/array/multilinestring.rs, src/io/geozero/array/multipoint.rs, src/io/geozero/array/multipolygon.rs, src/io/geozero/array/point.rs, src/io/geozero/array/polygon.rs, src/io/geozero/mod.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/302
=> Shorten name of geozero traits

src/array/linestring/builder.rs, src/array/mixed/builder.rs, src/io/geozero/array/linestring.rs, src/io/geozero/array/mixed.rs, src/io/geozero/array/mod.rs
Not sure that this fully works yet. I don't have time to test it right now. But it looks reasonably correct.
=> implement geozero traits for mixed array

src/io/geozero/array/mod.rs, src/io/geozero/mod.rs
Omitted from https://github.com/geoarrow/geoarrow-rs/pull/304
=> add mixed array geozero exports

python/core/Cargo.lock, python/core/Cargo.toml, python/core/src/array/primitive.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/294
=> Implement numpy `__array__` dunder for primitive array types

src/algorithm/geo/affine_ops.rs, src/algorithm/geo/rotate.rs, src/algorithm/geo/scale.rs, src/algorithm/geo/skew.rs, src/algorithm/geo/translate.rs, src/array/binary/array.rs, src/array/binary/builder.rs
=> simplify constructing wkb array from geometries

src/array/geometrycollection/builder.rs, src/array/geometrycollection/capacity.rs, src/array/geometrycollection/mod.rs, src/array/mixed/capacity.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/174
=> Implement geometry collection builder

src/io/wkb/writer/geometrycollection.rs
=> write wkb geometry collection using trait impl!!

Cargo.lock, src/algorithm/geo/area.rs, src/array/binary/array.rs, src/array/coord/combined/array.rs, src/array/coord/interleaved/array.rs, src/array/coord/separated/array.rs, src/array/geometry/array.rs, src/array/geometrycollection/array.rs, src/array/linestring/array.rs, src/array/mixed/array.rs, src/array/multilinestring/array.rs, src/array/multipoint/array.rs, src/array/multipolygon/array.rs, src/array/point/array.rs, src/array/polygon/array.rs, src/array/rect/array.rs, src/chunked_array/chunked_array.rs, src/chunked_array/mod.rs, src/lib.rs, src/trait_.rs
Once we implement geometry operations on `&dyn GeometryArrayTrait`, implementing them on the chunked versions should be straightforward.
=> proof of concept for chunked arrays

src/array/cast.rs, src/array/mod.rs
Inspired from https://docs.rs/arrow/latest/arrow/array/trait.AsArray.html as well as from @lewiszlw 's pr here: https://github.com/geoarrow/geoarrow-rs/pull/291/files#diff-900e8cb95ef27393b9ad89a00cddeb827988e2a78dd4163cdbd6b7adaec0fe1cR163-R177
=> downcasting helper

benches/nybb.rs, benches/wkb.rs, src/array/mod.rs, src/array/point/mod.rs, src/io/geos/scalar/multipolygon.rs, src/io/geos/scalar/polygon.rs, src/scalar/polygon/mod.rs, src/test/geoarrow_data/util.rs
=> fix clippy lints

Cargo.lock, Cargo.toml, python/core/Cargo.lock, python/core/Cargo.toml, src/algorithm/geo/area.rs, src/algorithm/geo/bounding_rect.rs, src/algorithm/geo/center.rs, src/algorithm/geo/centroid.rs, src/algorithm/geo/chaikin_smoothing.rs, src/algorithm/geo/convex_hull.rs, src/algorithm/geo/densify.rs, src/algorithm/geo/dimensions.rs, src/algorithm/geo/euclidean_length.rs, src/algorithm/geo/geodesic_area.rs, src/algorithm/geo/geodesic_length.rs, src/algorithm/geo/haversine_length.rs, src/algorithm/geo/minimum_rotated_rect.rs, src/algorithm/geo/simplify.rs, src/algorithm/geo/simplify_vw.rs, src/algorithm/geo/vincenty_length.rs, src/chunked_array/chunked_array.rs, src/chunked_array/mod.rs
If the `rayon` feature is enabled, automatically use rayon for chunked operations
=> Rayon feature on chunked arrays

python/core/src/algorithm/geo/area.rs, python/core/src/algorithm/geo/bounding_rect.rs, python/core/src/algorithm/geo/center.rs, python/core/src/algorithm/geo/centroid.rs, python/core/src/algorithm/geo/chamberlain_duquette_area.rs, python/core/src/algorithm/geo/convex_hull.rs, python/core/src/algorithm/geo/dimensions.rs, python/core/src/algorithm/geo/euclidean_length.rs, python/core/src/algorithm/geo/geodesic_area.rs, python/core/src/algorithm/geo/vincenty_length.rs, python/core/src/algorithm/native/concatenate.rs, python/core/src/array/mod.rs, python/core/src/error.rs, python/core/src/ffi/from_python.rs, python/core/src/ffi/to_python.rs, python/core/src/io/csv.rs, python/core/src/io/ewkb.rs, python/core/src/io/flatgeobuf.rs, python/core/src/io/geojson.rs, python/core/src/io/wkb.rs, python/core/src/io/wkt.rs, python/core/src/lib.rs
=> python: improved error handling

.github/workflows/python-docs.yml
https://stackoverflow.com/a/77412363
Closes #405
=> Add `pages: write` permission to python docs ci

src/io/geozero/api/ewkb.rs, src/io/geozero/api/wkt.rs, src/scalar/binary/scalar.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/410
=> remove ewkb copy

src/io/geojson_lines/reader.rs
https://docs.rs/geozero/latest/geozero/geojson/struct.GeoJsonLineReader.html, https://github.com/georust/geozero/pull/192
=> Use upstream geojson line reader

Cargo.lock, Cargo.toml
PROJ is not compiling on docs.rs and I don't want to debug it now
=> set docs.rs features

src/array/binary/array.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/243, closes https://github.com/geoarrow/geoarrow-rs/pull/248
=> fix iter geo for wkb array

src/algorithm/geo/area.rs, src/algorithm/geo/euclidean_length.rs, src/algorithm/geo/geodesic_length.rs, src/algorithm/geo/haversine_length.rs, src/algorithm/geo/vincenty_length.rs, src/trait_.rs
Doesn't really look like a speedup; doesn't save a lot of lines of code either 🤷‍♂️ 
Testing on https://github.com/geoarrow/geoarrow-rs/pull/468 gave results with no statistical significance
=> Add `unary_primitive`

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, build/README.md, build/pixi.lock, build/pixi.toml, examples/gdal.rs, src/error.rs, src/io/gdal/mod.rs, src/io/gdal/reader.rs, src/io/mod.rs
Based on https://github.com/georust/gdal/pull/518
=> Add read_gdal method

src/array/offset_builder.rs
See https://github.com/apache/arrow-rs/pull/5388
=> Use usize_as in offset builder

.github/workflows/python-docs.yml, .github/workflows/python.yml, docs/pyproject.toml, python/docs/empty_py/__init__.py, python/docs/pyproject.toml
Closes https://github.com/geoarrow/geoarrow-rs/issues/547
=> Poetry non package mode for docs envs

python/core/python/geoarrow/rust/core/_rust.pyi, python/core/python/geoarrow/rust/core/types.py, python/core/src/algorithm/geo/line_locate_point.rs, python/core/src/algorithm/geo/mod.rs, python/core/src/lib.rs, python/docs/source/api/core/functions.md, src/algorithm/geo/line_interpolate_point.rs, src/algorithm/geo/line_locate_point.rs, src/algorithm/geo/mod.rs
- **Line locate point**
- **line locate point**
=> Python: line locate point

python/core/Cargo.lock, python/core/src/ffi/to_python/array.rs, python/core/src/ffi/to_python/chunked.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/564
=> Fix arrow_c_array keyword arg name

python/core/Cargo.lock, python/core/python/geoarrow/rust/core/types.py, python/core/src/algorithm/geo/affine_ops.rs, python/core/src/algorithm/geo/frechet_distance.rs, python/core/src/algorithm/geo/line_interpolate_point.rs, python/core/src/algorithm/geo/line_locate_point.rs, python/core/src/algorithm/native/explode.rs, python/core/src/algorithm/polylabel.rs, python/core/src/interop/numpy/from_numpy.rs, python/core/src/interop/numpy/to_numpy.rs, python/docs/source/api/core/geometry/array.md, python/docs/source/api/core/geometry/chunked.md, python/docs/source/api/core/geometry/scalar.md, python/docs/source/api/core/primitive/array.md, src/algorithm/geo/frechet_distance.rs, src/algorithm/polylabel.rs
Getting ready for an 0.2 release
=> Improved docstrings

Cargo.toml, python/core/Cargo.lock, src/io/parquet/mod.rs, src/io/parquet/writer/async.rs, src/io/parquet/writer/mod.rs
=> Async GeoParquet writer

python/core/python/geoarrow/rust/core/_rust.pyi, python/core/python/geoarrow/rust/core/types.py, python/core/src/io/parquet/reader.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/627
=> Fix Python type hints for ParquetFile and ParquetDataset

src/table/mod.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/595
=> Convert record batch reader to table

python/core/src/array/mod.rs, src/datatypes.rs, src/io/wkb/reader/geometry.rs, src/io/wkb/reader/geometry_collection.rs, src/io/wkb/reader/linearring.rs, src/io/wkb/reader/linestring.rs, src/io/wkb/reader/maybe_multi_line_string.rs, src/io/wkb/reader/maybe_multi_point.rs, src/io/wkb/reader/maybe_multipolygon.rs, src/io/wkb/reader/multilinestring.rs, src/io/wkb/reader/multipoint.rs, src/io/wkb/reader/multipolygon.rs, src/io/wkb/reader/point.rs, src/io/wkb/reader/polygon.rs
This is some primary setup for reading 3d WKB buffers, but I can't really do anything here until geo-traits are expanded to 3d
=> wkb 3d reader setup

src/io/geozero/array/geometrycollection.rs, src/io/geozero/array/linestring.rs, src/io/geozero/array/mixed.rs, src/io/geozero/array/multilinestring.rs, src/io/geozero/array/multipoint.rs, src/io/geozero/array/multipolygon.rs, src/io/geozero/array/point.rs, src/io/geozero/array/polygon.rs, src/io/geozero/scalar/coord.rs, src/io/geozero/scalar/geometry.rs, src/io/geozero/scalar/geometry_collection.rs, src/io/geozero/scalar/linestring.rs, src/io/geozero/scalar/mod.rs, src/io/geozero/scalar/multilinestring.rs, src/io/geozero/scalar/multipoint.rs, src/io/geozero/scalar/multipolygon.rs, src/io/geozero/scalar/point.rs, src/io/geozero/scalar/polygon.rs, src/io/geozero/table/data_source.rs, src/io/wkb/reader/coord.rs
=> write 3d geometries through geozero

src/algorithm/native/type_id.rs, src/array/binary/builder.rs, src/array/binary/capacity.rs, src/io/wkb/common.rs, src/io/wkb/mod.rs, src/io/wkb/reader/geometry.rs, src/io/wkb/reader/mod.rs, src/io/wkb/reader/type.rs, src/io/wkb/writer/geometry.rs, src/io/wkb/writer/geometrycollection.rs, src/io/wkb/writer/linestring.rs, src/io/wkb/writer/mod.rs, src/io/wkb/writer/multilinestring.rs, src/io/wkb/writer/multipoint.rs, src/io/wkb/writer/multipolygon.rs, src/io/wkb/writer/point.rs, src/io/wkb/writer/polygon.rs
=> write 3d geometries to wkb

src/array/binary/array.rs, src/array/geometrycollection/array.rs, src/array/linestring/array.rs, src/array/metadata.rs, src/array/mixed/array.rs, src/array/multilinestring/array.rs, src/array/multipoint/array.rs, src/array/multipolygon/array.rs, src/array/point/array.rs, src/array/polygon/array.rs, src/array/rect/array.rs
=> Don't serialize empty array metadata

src/datatypes.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/682
=> fix dimension parsing in mixed data type

js/Cargo.lock, js/Cargo.toml
Ref https://github.com/H-Plus-Time/object-store-wasm/issues/42
=> Bump object-store-wasm to 0.0.5

src/array/binary/array.rs, src/array/coord/interleaved/array.rs, src/array/geometrycollection/array.rs, src/array/linestring/array.rs, src/array/mixed/array.rs, src/array/multilinestring/array.rs, src/array/multipoint/array.rs, src/array/multipolygon/array.rs, src/array/point/array.rs, src/array/polygon/array.rs, src/array/rect/array.rs, src/datatypes.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/679
=> deduplicate field creation

src/io/geozero/table/data_source.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/715
=> Support MapArrays when exporting to geozero

python/core/pyproject.toml, python/proj/pyproject.toml
Closes https://github.com/geoarrow/geoarrow-rs/issues/704
=> Set version to be dynamic in pyproject.toml

python/core/src/array/getitem.rs, python/core/src/chunked_array/getitem.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/722
=> Python: Fix array indexing with negative integers

src/algorithm/native/bounding_rect.rs, src/algorithm/native/map_coords.rs, src/array/mod.rs, src/chunked_array.rs, src/geo_traits/coord.rs, src/io/geozero/table/data_source.rs, src/scalar/geometry/owned.rs, src/scalar/geometrycollection/owned.rs, src/scalar/linestring/owned.rs, src/scalar/multilinestring/owned.rs, src/scalar/multipoint/owned.rs, src/scalar/multipolygon/owned.rs, src/scalar/point/owned.rs, src/scalar/polygon/owned.rs, src/scalar/rect/owned.rs, src/scalar/rect/scalar.rs
- Fix BoundingRect declared dimension
- Update RectTrait to use const dim generic array instead of tuple
- Support for 3d array downcasting
- Implement CoordTrait for `[f64; D]`
=> implement geo traits for 3d owned geometries

js/src/io/parquet/async.rs, js/src/io/parquet/options.rs, python/core/Cargo.lock, python/core/Cargo.toml, python/core/src/error.rs, python/core/src/io/parquet/options.rs, python/core/src/io/parquet/reader.rs, src/io/parquet/metadata.rs, src/io/parquet/mod.rs, src/io/parquet/reader/async.rs, src/io/parquet/reader/builder.rs, src/io/parquet/reader/metadata.rs, src/io/parquet/reader/mod.rs, src/io/parquet/reader/options.rs, src/io/parquet/reader/spatial_filter.rs
Don't require the user to pass in bounding-box columns if the covering field exists
=> Use GeoParquet 1.1 covering field

python/core/poetry.lock, python/core/src/array/mod.rs, python/core/src/chunked_array/mod.rs, python/core/src/io/input/sync.rs, python/core/src/scalar/mod.rs, python/core/tests/test_array.py, src/chunked_array.rs
- Restore `__geo_interface__` method on GeometryArray
- Restore `__getitem__`, `__len__` on ChunkedGeometryArray
=> Python fixes

CHANGELOG.md, Cargo.lock, Cargo.toml, python/CHANGELOG.md, python/Cargo.lock, python/Cargo.toml
Closes https://github.com/geoarrow/geoarrow-rs/issues/628
=> Bump to 0.3

src/io/flatgeobuf/reader/core.rs, src/io/flatgeobuf/reader/mod.rs
This is preparatory work for in the future using Flatgeobuf objects directly instead of going through geozero.
=> Implement geo-traits on Flatgeobuf geometry objects

python/tests/interop/test_wkb.py, src/array/geometrycollection/array.rs, src/io/wkb/api.rs, src/io/wkb/reader/geometry.rs, src/io/wkb/reader/geometry_collection.rs, src/io/wkb/reader/multipolygon.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/786
=> Fix parsing WKB GeometryCollection

python/docs/api/core/functions.md, python/geoarrow-core/python/geoarrow/rust/core/_rust.pyi, python/geoarrow-core/src/interop/wkt.rs, src/array/mod.rs, src/chunked_array/dynamic.rs, src/io/wkb/api.rs, src/io/wkt/mod.rs, src/io/wkt/writer/api.rs, src/io/wkt/writer/mod.rs, src/io/wkt/writer/scalar.rs
closes https://github.com/geoarrow/geoarrow-rs/issues/762
=> Public API for to_wkt

python/docs/api/core/geometry/chunked.md, python/geoarrow-compute/python/geoarrow/rust/compute/_compute.pyi, python/geoarrow-compute/python/geoarrow/rust/compute/types.py, python/geoarrow-core/python/geoarrow/rust/core/_rust.pyi, python/geoarrow-io/python/geoarrow/rust/io/types.py, python/mkdocs.yml
Closes https://github.com/geoarrow/geoarrow-rs/issues/793
=> Fix doc links

python/geoarrow-compute/src/algorithm/geo/affine_ops.rs, python/geoarrow-compute/src/algorithm/geo/area.rs, python/geoarrow-compute/src/algorithm/geo/center.rs, python/geoarrow-compute/src/algorithm/geo/centroid.rs, python/geoarrow-compute/src/algorithm/geo/chaikin_smoothing.rs, python/geoarrow-compute/src/algorithm/geo/convex_hull.rs, python/geoarrow-compute/src/algorithm/geo/densify.rs, python/geoarrow-compute/src/algorithm/geo/dimensions.rs, python/geoarrow-compute/src/algorithm/geo/envelope.rs, python/geoarrow-compute/src/algorithm/geo/frechet_distance.rs, python/geoarrow-compute/src/algorithm/geo/geodesic_area.rs, python/geoarrow-compute/src/algorithm/geo/length.rs, python/geoarrow-compute/src/algorithm/geo/line_interpolate_point.rs, python/geoarrow-compute/src/algorithm/geo/line_locate_point.rs, python/geoarrow-compute/src/algorithm/geo/rotate.rs, python/geoarrow-compute/src/algorithm/geo/scale.rs, python/geoarrow-compute/src/algorithm/geo/simplify.rs, python/geoarrow-compute/src/algorithm/geo/skew.rs, python/geoarrow-compute/src/algorithm/geo/translate.rs, python/geoarrow-compute/src/algorithm/native/total_bounds.rs, python/geoarrow-compute/src/algorithm/polylabel.rs, python/geoarrow-compute/src/ffi/from_python/input.rs, python/geoarrow-compute/src/ffi/from_python/mod.rs, python/geoarrow-core/src/ffi/from_python/input.rs, python/geoarrow-core/src/ffi/from_python/mod.rs, python/geoarrow-core/src/interop/wkb.rs, python/geoarrow-core/src/interop/wkt.rs, src/datatypes.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/783
=> Better errors when parsing to a native type

python/geoarrow-core/python/geoarrow/rust/core/_constructors.pyi, python/geoarrow-core/src/constructors.rs, python/geoarrow-core/src/interop/shapely/from_shapely.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/806
=> Reuse buffers zero-copy in from_shapely

python/geoarrow-core/python/geoarrow/rust/core/_constructors.pyi, python/geoarrow-core/python/geoarrow/rust/core/_rust.pyi, python/geoarrow-core/python/geoarrow/rust/core/types.py
Closes https://github.com/geoarrow/geoarrow-rs/issues/813
=> Better typing for CRS input

src/io/flatgeobuf/reader/async.rs, src/io/flatgeobuf/reader/common.rs, src/io/flatgeobuf/reader/sync.rs, src/io/geozero/table/builder/anyvalue.rs, src/io/geozero/table/builder/properties.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/730
=> Set arrow.json extension type on geozero JSON type

python/Cargo.lock, python/Cargo.toml, python/geoarrow-compute/Cargo.toml, python/geoarrow-compute/src/algorithm/geo/area.rs, python/geoarrow-compute/src/broadcasting/primitive.rs, python/geoarrow-core/Cargo.toml, python/geoarrow-core/src/interop/shapely/from_shapely.rs, python/geoarrow-io/Cargo.toml, python/geoarrow-io/src/error.rs, python/geoarrow-io/src/io/flatgeobuf/async.rs, python/geoarrow-io/src/io/input/sync.rs, python/geoarrow-io/src/io/object_store/store.rs, python/geoarrow-io/src/io/parquet/async.rs, python/geoarrow-io/src/io/parquet/options.rs, python/geoarrow-io/src/io/parquet/sync.rs, python/geoarrow-io/src/io/postgis.rs, python/pyo3-geoarrow/src/array.rs, python/pyo3-geoarrow/src/chunked_array.rs, python/pyo3-geoarrow/src/coord_type.rs, python/pyo3-geoarrow/src/data_type.rs, python/pyo3-geoarrow/src/dimension.rs, python/pyo3-geoarrow/src/error.rs, python/pyo3-geoarrow/src/scalar.rs
Preparatory work for testing integration with pyo3-object-store.
=> Bump to pyo3 0.22

rust/geoarrow/src/array/mixed/array.rs, rust/geoarrow/src/array/offset_builder.rs, rust/geoarrow/src/array/util.rs
=> Modify code comment inconsistency

Cargo.lock, rust/geoarrow/Cargo.toml, rust/geoarrow/src/array/binary/builder.rs, rust/geoarrow/src/array/binary/capacity.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/857
=> Bump wkt and wkb deps

python/geoarrow-io/python/geoarrow/rust/io/_io.pyi
Closes https://github.com/geoarrow/geoarrow-rs/issues/835
=> Fix io docstrings to import from geoarrow.rust.io

rust/geoarrow/src/io/flatgeobuf/writer.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/198
=> Add flatgeobuf test with not writing index

docs/README.md, docs/source/index.md, docs/source/stylesheets/extra.css
Closes https://github.com/geoarrow/geoarrow-rs/issues/774
=> Update docs root page

python/Cargo.lock, python/geoarrow-io/Cargo.toml
=> Fix pyodide compilation

docs/source/index.md
Closes https://github.com/geoarrow/geoarrow-rs/issues/773
=> Remove backticks on the root home page

.github/workflows/ci.yml
Closes https://github.com/geoarrow/geoarrow-rs/issues/836
=> fix benchmarks ci

python/geoarrow-io/python/geoarrow/rust/io/_csv.pyi, python/geoarrow-io/src/error.rs, python/geoarrow-io/src/io/csv.rs, python/tests/io/test_csv.py, rust/geoarrow/src/io/csv/mod.rs, rust/geoarrow/src/io/csv/reader.rs
Follow up from https://github.com/geoarrow/geoarrow-rs/pull/646
Closes https://github.com/geoarrow/geoarrow-rs/issues/613
cc @gadomski
=> Use arrow-csv for reading csv data

python/docs/api/core/functions.md, python/geoarrow-io/python/geoarrow/rust/io/_csv.pyi, python/geoarrow-io/python/geoarrow/rust/io/_shapefile.pyi, python/geoarrow-io/src/io/shapefile.rs, python/tests/io/test_shapefile.py, rust/geoarrow/src/io/flatgeobuf/reader/common.rs, rust/geoarrow/src/io/shapefile/mod.rs, rust/geoarrow/src/io/shapefile/reader.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/871
=> Read CRS in shapefile reader

rust/geoarrow/src/algorithm/native/unary.rs, rust/geoarrow/src/array/geometry/builder.rs, rust/geoarrow/src/array/geometrycollection/builder.rs, rust/geoarrow/src/array/linestring/builder.rs, rust/geoarrow/src/array/mixed/builder.rs, rust/geoarrow/src/array/multilinestring/builder.rs, rust/geoarrow/src/array/multipoint/builder.rs, rust/geoarrow/src/array/multipolygon/builder.rs, rust/geoarrow/src/array/point/builder.rs, rust/geoarrow/src/array/polygon/builder.rs, rust/geoarrow/src/io/wkb/api.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/920
=> Don't use Option<CoordType> in builders

python/geoarrow-io/python/geoarrow/rust/io/_csv.pyi, python/geoarrow-io/src/io/csv.rs, python/tests/io/test_csv.py, rust/geoarrow/src/io/csv/mod.rs, rust/geoarrow/src/io/csv/reader.rs, rust/geoarrow/src/io/stream.rs
For https://github.com/geoarrow/geoarrow-rs/issues/594, for https://github.com/geoarrow/geoarrow-rs/issues/596.
=> Return RecordBatchReader in CSV read API

CHANGELOG.md
closes https://github.com/geoarrow/geoarrow-rs/issues/963
=> chore: add GeometryArrayAccessor to changelog

rust/geoarrow/src/scalar/point/scalar.rs
Ref https://github.com/geoarrow/geoarrow-rs/pull/970#discussion_r1903087709
=> Use `AABB::from_point` instead of creating bounding box from point

js/Cargo.toml, rust/geoarrow/src/array/linestring/array.rs, rust/geoarrow/src/array/multilinestring/array.rs, rust/geoarrow/src/array/multipoint/array.rs, rust/geoarrow/src/array/multipolygon/array.rs, rust/geoarrow/src/array/point/array.rs, rust/geoarrow/src/array/polygon/array.rs
For https://github.com/geoarrow/geoarrow-rs/pull/984
=> Fix clippy

Cargo.lock, js/Cargo.lock, js/Cargo.toml, python/Cargo.lock, python/Cargo.toml, python/proj/Cargo.toml, rust/geoarrow/Cargo.toml
Pin pyo3 to 0.23.3: https://github.com/PyO3/pyo3/issues/4909
=> Bump flatgeobuf to 4.6

Cargo.lock, rust/geoarrow/Cargo.toml, rust/geoarrow/src/algorithm/geo_index/rtree.rs, rust/geoarrow/src/indexed/array.rs
Closes https://github.com/geoarrow/geoarrow-rs/pull/980
=> Bump geo-index to 0.2

rust/geoarrow/src/table.rs
In `Table::from_arrow_and_geometry` it can be helpful to keep the schema's metadata on the output table. Discovered while working https://github.com/stac-utils/stac-rs/issues/676
=> fix: keep schema metadata

python/Cargo.lock, python/geoarrow-io/Cargo.toml, python/geoarrow-io/python/geoarrow/rust/io/_flatgeobuf.pyi, python/geoarrow-io/src/io/flatgeobuf/sync.rs, python/geoarrow-io/src/io/input/sync.rs
Ref https://github.com/omerbenamram/pyo3-file/pull/28
=> Remove vendor of pyo3-file

rust/geoarrow-schema/src/crs.rs, rust/geoarrow-schema/src/dimension.rs, rust/geoarrow-schema/src/metadata.rs
Mostly a productive way for me to learn how to use this properly. Happy to iterate if my Rust or GeoArrow usage is off!
=> Add additional tests for crs, dimension, and metadata modules

rust/geoarrow-array/src/array/wkb.rs, rust/geoarrow-array/src/array/wkt.rs
- Update `TryFrom` implementations from `&dyn Array` for `WKTArray` and `WKBArray` to take in a `WktType`/`WkbType` as well
- Add tests for parsing from an `Array` to `WKTArray` / `WKBArray`
=> Update downcasting Array to WKBArray and WKTArray

rust/geoarrow-array/src/array/coord/separated.rs, rust/geoarrow-array/src/array/rect.rs, rust/geoarrow-array/src/builder/coord/interleaved.rs, rust/geoarrow-array/src/builder/coord/separated.rs, rust/geoarrow-array/src/builder/mixed.rs, rust/geoarrow-array/src/builder/polygon.rs, rust/geoarrow-array/src/builder/rect.rs, rust/geoarrow-array/src/builder/wkb.rs, rust/geoarrow-array/src/capacity/wkb.rs, rust/geoarrow-array/src/datatypes.rs, rust/geoarrow-array/src/scalar/coord/interleaved.rs, rust/geoarrow-array/src/scalar/coord/separated.rs, rust/pyo3-geoarrow/src/coord_buffer.rs
- [Fix pushing rect to PolygonBuilder](https://github.com/geoarrow/geoarrow-rs/commit/de6e76e53e8f381b1418eefcbf28cb8e6cfb2ff1)
- [Simplify writing geometry to WkbBuilder](https://github.com/geoarrow/geoarrow-rs/commit/c6f380c7f04b2b241d79648c1d563fbc689e8887) 
- [Remove push_box2d from RectBuilder](https://github.com/geoarrow/geoarrow-rs/commit/f280ace4fc5741431ecd101ba0edb4a4aedaff33)
- [Fix inference of GeoArrowType from field without extension metadata](https://github.com/geoarrow/geoarrow-rs/commit/a047ae8c8c83665666d0a64b6107eec5319237b8)
- [Remove unused methods from MixedGeometryBuilder](https://github.com/geoarrow/geoarrow-rs/commit/1c559374e158d201b9fb23c916891409d1f575da)
- [Validate compatible dimensions when pushing coords to coord …
=> Fix miscellaneous TODOs

Cargo.lock, Cargo.toml
=> Bump to wkt 0.13

rust/geodatafusion/src/udf/native/io/mod.rs, rust/geodatafusion/src/udf/native/io/wkb.rs, rust/geodatafusion/src/udf/native/io/wkt.rs, rust/geodatafusion/src/udf/native/mod.rs
- Add `AsText`, `AsBinary`, `GeomFromText`, `GeomFromWKB` scalar UDFs to geodatafusion
=> GeoDataFusion: AsText, AsBinary, GeomFromText, GeomFromWKB

Cargo.lock, rust/geodatafusion/Cargo.toml, rust/geodatafusion/src/udf/native/constructors/mod.rs, rust/geodatafusion/src/udf/native/constructors/point.rs
- Add `ST_PointZ`, `ST_PointM`, `ST_PointZM`, `ST_MakePoint`, `ST_MakePointM`
- Add SRID support to the `ST_Point*` functions
=> Add `ST_PointZ`, `ST_PointM`, `ST_PointZM`, `ST_MakePoint`, `ST_MakePointM`

rust/geoarrow-array/src/array/mixed.rs, rust/geoarrow-array/src/array/wkb.rs, rust/geoarrow-array/src/array/wkb_view.rs, rust/geoarrow-array/src/array/wkt.rs, rust/geoarrow-array/src/array/wkt_view.rs, rust/geoarrow-array/src/cast.rs, rust/geoarrow-array/src/datatypes.rs, rust/geoarrow-array/src/scalar/mod.rs, rust/geoarrow-array/src/trait_.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/1117, closes https://github.com/geoarrow/geoarrow-rs/issues/1116
Some other various docs updates.
=> Restore ignored doctests

.github/workflows/ci.yml, rust/geoarrow-array/README.md, rust/geoarrow-array/src/array/geometry.rs, rust/geoarrow-array/src/array/geometrycollection.rs, rust/geoarrow-array/src/array/linestring.rs, rust/geoarrow-array/src/array/mixed.rs, rust/geoarrow-array/src/array/mod.rs, rust/geoarrow-array/src/array/multilinestring.rs, rust/geoarrow-array/src/array/multipoint.rs, rust/geoarrow-array/src/array/multipolygon.rs, rust/geoarrow-array/src/array/point.rs, rust/geoarrow-array/src/array/polygon.rs, rust/geoarrow-array/src/array/rect.rs, rust/geoarrow-array/src/array/wkb.rs, rust/geoarrow-array/src/array/wkb_view.rs, rust/geoarrow-array/src/array/wkt.rs, rust/geoarrow-array/src/array/wkt_view.rs, rust/geoarrow-array/src/builder/offsets.rs, rust/geoarrow-array/src/datatypes.rs, rust/geoarrow-array/src/geozero/export/scalar/point.rs, rust/geoarrow-array/src/scalar/mod.rs, rust/geoarrow-array/src/trait_.rs, rust/geoarrow-geoparquet/src/metadata.rs, rust/geoarrow-geoparquet/src/reader/builder.rs, rust/geoarrow-geoparquet/src/reader/options.rs, rust/geoarrow-schema/src/metadata.rs, rust/geoarrow-test/src/raw/mod.rs, rust/pyo3-geoarrow/src/chunked_array.rs, rust/pyo3-geoarrow/src/crs.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/1122
=> Ensure on CI that docs build without warnings

Cargo.lock, Cargo.toml, python/Cargo.lock
For https://github.com/geoarrow/geoarrow-rs/issues/1098
=> Use released wkb version 0.9

Cargo.lock, Cargo.toml, js/Cargo.lock, python/Cargo.lock, rust/geoarrow-test/Cargo.toml
I haven't published workspace crates before so I'll probably go through a few iterations of beta versions to test out different workflows for workspace publishing
=> Bump to 0.4.0-beta.4

rust/geoarrow-cast/Cargo.toml, rust/geoarrow-cast/README.md, rust/geoarrow-cast/src/cast.rs, rust/geoarrow-cast/src/downcast.rs, rust/geoarrow-cast/src/lib.rs
- Improved docs for geoarrow-cast
- Added `#![warn(missing_docs)]`
- Support for `WkbView` and `WktView` source and destination types in `cast`
=> feat(geoarrow-cast): Support WkbView and WktView in `cast`; improved docs

rust/geoarrow-array/src/util.rs
=> chore: Elide lifetime

Cargo.lock, Cargo.toml, python/Cargo.lock, python/Cargo.toml, python/geoarrow-io/Cargo.toml
Bump pyo3 to 0.25. Closes #1164
=> chore: Bump pyo3 to 0.25

Cargo.lock, Cargo.toml, python/Cargo.lock, python/geoarrow-core/python/geoarrow/rust/core/_array_reader.pyi, python/geoarrow-core/python/geoarrow/rust/core/_rust.pyi, python/geoarrow-core/src/lib.rs, rust/pyo3-geoarrow/src/array_reader.rs, rust/pyo3-geoarrow/src/lib.rs
Supports a _stream_ of GeoArrow arrays that have been validated to be a valid GeoArrow type
=> feat(Python): Add GeoArrowArrayReader

.github/workflows/python.yml, python/docs/DEVELOP.md, python/docs/api/core/geometry/type.md, python/docs/api/io/geoparquet.md, python/docs/performance/multithreading.md, python/geoarrow-compute/python/geoarrow/rust/compute/_compute.pyi, python/geoarrow-core/python/geoarrow/rust/core/_rust.pyi, python/geoarrow-io/python/geoarrow/rust/io/_flatgeobuf.pyi, python/geoarrow-io/python/geoarrow/rust/io/_parquet.pyi, python/geoarrow-io/python/geoarrow/rust/io/_shapefile.pyi, python/geoarrow-io/python/geoarrow/rust/io/types.py, python/mkdocs.yml
For https://github.com/geoarrow/geoarrow-rs/issues/1175
=> ci(python): Validate Python docs build without errors

.github/workflows/python.yml
Note that this is the same failure as https://github.com/kylebarron/arro3/issues/343
=> ci: Turn off failing pyodide io wheel test

python/docs/api/core/geometry_type.md, python/geoarrow-core/python/geoarrow/rust/core/_data_type.pyi
For https://github.com/geoarrow/geoarrow-rs/issues/1175
=> docs(Python): Show `large_wkb`, `wkb_view`, `large_wkt`, `wkt_view` constructors

rust/pyo3-geoarrow/src/array_reader.rs, rust/pyo3-geoarrow/src/input.rs, rust/pyo3-geoarrow/src/lib.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/1086
=> feat(python): Add `AnyGeoArray` for abstracting over either array or stream input

Cargo.lock, python/Cargo.lock, python/Cargo.toml
=> chore(Python): Bump to 0.4.0-beta.5

rust/geoarrow-array/src/array/coord/interleaved.rs, rust/geoarrow-array/src/trait_.rs
Fix problems mentioned in #1200.
=> fix(geoarrow-array): inconsistencies between code and comment

python/CHANGELOG.md, python/Cargo.lock, python/Cargo.toml, python/docs/api/core/geometry/scalar.md, python/mkdocs.yml
Closes https://github.com/geoarrow/geoarrow-rs/issues/1175
=> chore(python): Prepare for 0.4.0 release

rust/pyo3-geoarrow/src/crs.rs
I.e., PROJJSON CRS that doesn't have a CRS Type defined
=> fix(Python): Fix exporting CRS to Pyproj for GeoArrow 0.1 metadata

CHANGELOG.md
Added changelog
Closes https://github.com/geoarrow/geoarrow-rs/issues/1212
=> chore(geoparquet): prepare for 0.4 release

python/geoarrow-io/python/geoarrow/rust/io/_parquet.pyi, python/geoarrow-io/src/parquet/async.rs, python/tests/io/test_parquet.py
Closes https://github.com/geoarrow/geoarrow-rs/issues/1223
=> feat(python): Add `path` property to GeoParquetFile

rust/geodatafusion/src/udf/native/bounding_box/extent.rs
As @timsaucer mentioned here https://github.com/apache/datafusion/issues/16997#issuecomment-3141356314, we can compute the input field into the accumulator by using [`PhysicalExpr::return_field`](https://docs.rs/datafusion/latest/datafusion/physical_expr/trait.PhysicalExpr.html#method.return_field)
=> fix(geodatafusion): Fix input field of ST_Extent

python/geoarrow-io/src/flatgeobuf/sync.rs, python/geoarrow-io/src/parquet/async.rs, python/geoarrow-io/src/parquet/sync.rs
Ref https://github.com/developmentseed/obstore/pull/451. This may be related to https://github.com/geoarrow/geoarrow-rs/issues/992
=> fix(geoarrow-python-io): Release GIL when blocking tokio runtime

rust/geodatafusion/README.md, rust/geodatafusion/src/udf/native/bounding_box/box.rs, rust/geodatafusion/src/udf/native/bounding_box/extent.rs, rust/geodatafusion/src/udf/native/bounding_box/extrema.rs, rust/geodatafusion/src/udf/native/bounding_box/mod.rs, rust/geodatafusion/src/udf/native/bounding_box/util/bounds.rs, rust/geodatafusion/src/udf/native/io/wkt.rs
Still need to add tests for zmin and zmax
=> feat(geodatafusion): `Box3D`, `ST_ZMin`, `ST_ZMax` UDFs

.github/workflows/python-core-wheels.yml, .github/workflows/python-docs.yml, .github/workflows/python-io-wheels.yml, .github/workflows/python.yml
=> ci: Build Python 3.13 wheels on Windows

rust/geoarrow-array/src/lib.rs, rust/geoarrow-array/src/wrap_array.rs, rust/geoarrow-csv/src/writer.rs, rust/geoarrow/src/array.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/1026
This is some syntactic sugar to make it nicer to construct GeoArrow arrays if you have an extension type and an Arrow Array
=> feat(geoarrow-array): WrapArray trait
