geoarrow/geoarrow-rs

js/Cargo.lock, js/Cargo.toml, js/src/lib.rs
wee alloc is marked as a security vuln. Also we do a lot of allocations and the extra size of the normal rust allocator is almost certainly worth it. https://github.com/Craig-Macomber/lol_alloc is better maintained than wee alloc but it says the normal allocator is only 5kb
=> js: Remove wee alloc

js/src/algorithm/geo/affine_ops.rs, js/src/algorithm/geo/rotate.rs, src/algorithm/geo/affine_ops.rs, src/algorithm/geo/euclidean_distance.rs, src/algorithm/geo/rotate.rs
For the _rust_ bindings, now that the wrappers are implemented in terms of traits, it allows us to do cool stuff like avoiding dealing with `Broadcastable...` and just calling them on array or scalar objects directly:
```rs
fn point_array() -> PointArray {
todo!()
}
fn point<'a>() -> Point<'a> {
todo!()
}
fn tmp() {
let point_array = point_array();
let point = point();
let a = point_array.euclidean_distance(&point_array);
let b = x.euclidean_distance(&point);
}
```
The other bindings will need to still have some sort of `Broadcastable` object
=> start implementing algorithm traits on both arrays and scalars

src/algorithm/geo/center.rs, src/algorithm/geo/centroid.rs, src/array/coord/combined/mutable.rs, src/array/coord/interleaved/mutable.rs, src/array/coord/separated/mutable.rs, src/array/linestring/mutable.rs, src/array/multilinestring/mutable.rs, src/array/multipoint/mutable.rs, src/array/multipolygon/mutable.rs, src/array/point/mutable.rs, src/array/polygon/mutable.rs
- Add `push_point`, `push_line_string`, etc, methods on the mutable arrays that take as input an `Option` of something that implements a geometry access trait
- Refactor `first_pass` to only compute _capacities_. This is strictly improved from what we have now, because we don't know exactly how many ring offsets to allocate before looping through the array once.
- Refactor `second_pass` to use the `push_*` methods, for simplicity and DRY
- Add `capacity` method to coord buffer structs to get the currently reserved capacity
=> Update mutable array

src/array/coord/combined/array.rs, src/array/coord/interleaved/array.rs, src/array/coord/separated/array.rs, src/scalar/binary/scalar.rs, src/scalar/coord/combined/scalar.rs, src/scalar/coord/interleaved/scalar.rs, src/scalar/coord/separated/scalar.rs, src/scalar/linestring/scalar.rs, src/scalar/multilinestring/scalar.rs, src/scalar/multipoint/scalar.rs, src/scalar/multipolygon/scalar.rs, src/scalar/point/scalar.rs, src/scalar/polygon/scalar.rs, src/scalar/rect/scalar.rs
- Implemented `PartialEq` for the various `CoordBuffer` and `Coord` types.
- In particular, the derived `PartialEq` called it on all constituent types. But if you have a scalar that's a reference on a larger array, then it would indicate `false` if _any_ item in the array were unequal, not just the specific point of interest.
Closes https://github.com/kylebarron/geoarrow-rs/issues/80
=> Fixed `PartialEq` for CoordBuffer and Scalars

src/array/linestring/array.rs, src/array/mixed/array.rs, src/array/mixed/iterator.rs, src/array/mixed/mod.rs, src/array/mixed/mutable.rs, src/array/mod.rs, src/array/multilinestring/array.rs, src/array/multilinestring/mutable.rs, src/array/multipoint/array.rs, src/array/multipolygon/array.rs, src/array/multipolygon/mutable.rs, src/array/point/array.rs, src/array/polygon/array.rs, src/scalar/geometry/geos.rs, src/scalar/geometry/mod.rs
This is an implementation of an array of geometries of mixed type. It uses an equivalent storage to the `arrow2` `UnionArray`.
On top of this, we can implement (non-nested) geometry collections in the future, using a list of this mixed array. If we really want full simple features compliance, we could allow that `GeometryCollectionArray` to be a child of this `MixedGeometryArray`, enabling (in theory!) nested geometry collections.
=> Mixed geometry array

Cargo.lock, Cargo.toml, js/Cargo.lock, js/src/array/geometry.rs, src/algorithm/geo/bounding_rect.rs, src/algorithm/geo/dimensions.rs, src/algorithm/geo/utils.rs, src/algorithm/geodesy/reproject.rs, src/algorithm/native/mod.rs, src/algorithm/native/type_id.rs, src/array/geometry/array.rs, src/io/geos/scalar/geometry.rs, src/io/native/wkb/geometry.rs, src/io/native/wkb/mod.rs, src/io/native/wkb/type.rs, src/scalar/geometry/scalar.rs
- Remove `WKB` variant from `GeometryArray` and `Geometry`
- Add `TypeIds` trait to get the geometry types from an array of geometries.
- Implement parsing from `WKBArray` to an arrow-native `GeometryArray`
Closes https://github.com/kylebarron/geoarrow-rs/issues/153, closes https://github.com/kylebarron/geoarrow-rs/issues/87
=> Remove `WKB` variant from GeometryArray and Geometry

.gitignore, src/array/binary/mutable.rs, src/io/wkb/mod.rs, src/io/wkb/reader/geometry.rs, src/io/wkb/writer/linestring.rs, src/io/wkb/writer/mod.rs, src/io/wkb/writer/multilinestring.rs, src/io/wkb/writer/multipoint.rs, src/io/wkb/writer/multipolygon.rs, src/io/wkb/writer/point.rs, src/io/wkb/writer/polygon.rs, src/scalar/binary/scalar.rs
Implements fast WKB writing from arrays of geometries.
For converting from arrays of geometries to a `WKBArray`, this does a two-pass approach. First it loops over all geometries to compute the output size of the encoded WKB geometry, adding this number to the offset array. Then it instantiates a values array with this known size and writes WKB geometries into this array. So it's able to only provision memory once.
=> Implement WKB writing

src/algorithm/mod.rs, src/algorithm/rstar.rs, src/array/binary/array.rs, src/array/coord/combined/array.rs, src/array/coord/interleaved/array.rs, src/array/coord/separated/array.rs, src/array/geometry/array.rs, src/array/geometrycollection/array.rs, src/array/linestring/array.rs, src/array/mixed/array.rs, src/array/multilinestring/array.rs, src/array/multipoint/array.rs, src/array/multipolygon/array.rs, src/array/point/array.rs, src/array/polygon/array.rs, src/array/rect/array.rs, src/trait_.rs
- Create new `algorithm/rstar` mod
- Remove rstar from `GeometryArrayTrait`. This is nice because simplifying the trait will probably make other things easier in the future, like using `impl GeometryArrayTrait` in places or `Box<dyn GeometryArrayTrait>` like how arrow2 has `Box<dyn Array>` in places. Right now, that's not really doable for me because I have associated types that have to be defined
Closes https://github.com/geoarrow/geoarrow-rs/issues/175
=> Put rstar creation inside trait

src/array/linestring/array.rs, src/array/multilinestring/array.rs, src/array/multipoint/array.rs, src/array/multipolygon/array.rs, src/array/polygon/array.rs, src/io/geos/array/linestring.rs, src/io/geos/array/multilinestring.rs, src/io/geos/array/multipoint.rs, src/io/geos/array/multipolygon.rs, src/io/geos/array/polygon.rs, src/io/wkb/writer/linestring.rs, src/io/wkb/writer/multilinestring.rs, src/io/wkb/writer/multipoint.rs, src/io/wkb/writer/multipolygon.rs, src/io/wkb/writer/polygon.rs
- Restore some commented tests
- Remove `#[allow(unused_variables)]`
=> Restore commented tests

.vscode/settings.json, js/.vscode/settings.json, python/.vscode/settings.json
If you have the [`peacock` extension](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) installed, this will open up a different window color for the python, js, and rust workspaces
=> Add vscode workspace colors

src/array/coord/mod.rs, src/array/linestring/mutable.rs, src/array/multilinestring/mutable.rs, src/array/multipoint/mutable.rs, src/array/multipolygon/mutable.rs, src/array/point/mutable.rs, src/array/polygon/mutable.rs, src/io/geos/array/point.rs
- Add `new_with_options`, `with_capacities_and_options`, etc that allow defining the coord type of the generated arrays (either interleaved or separated)
- Convert the existing `first_pass` and `second_pass` functions for each mutable array into a private `count_from_iter` that takes in an iterable of geometries (implemented from traits) and an `extend_from_iter` that fills geometries into the array, whether or not they've been pre-allocated.
So this is exposed to the end user as e.g. `from_line_strings` which takes in a slice of `impl LineStringTrait` and creates a `MutableLineStringArray` with the exact allocations. This makes the `From` impls super simple
- Add `Default` for `CoordType`, setting it to `Interleaved`
=> Enable setting coord type when creating mutable arrays

Cargo.toml, benches/from_geo.rs, src/geo_traits/geometry.rs, src/geo_traits/geometry_collection.rs, src/geo_traits/line_string.rs, src/geo_traits/multi_line_string.rs, src/geo_traits/multi_point.rs, src/geo_traits/multi_polygon.rs, src/geo_traits/polygon.rs
- this should be copied into geo as well
- I wonder if there's a perf improvement from the removed cloning
- It would be nice to make a quick bench before merging
=> remove cloning from geo iterators in trait

python/core/python/geoarrow/rust/core/__init__.py, python/core/src/array/binary.rs, python/core/src/array/mod.rs, python/core/src/array/primitive.rs, python/core/src/ffi/from_python.rs, python/core/src/ffi/mod.rs, python/core/src/ffi/to_python.rs, python/core/src/lib.rs
It works round trip!
```py
import pyarrow as pa
import shapely
import pandas as pd
import geopandas as gpd
from geoarrow.rust.core import WKBArray
gdf = gpd.read_file(gpd.datasets.get_path('nybb'))
large_gdf = pd.concat([gdf] * 1000)
wkb = shapely.to_wkb(large_gdf['geometry'])
pa_wkb_arr = pa.array(wkb)
rust_wkb_arr = WKBArray.from_arrow(pa_wkb_arr)
rust_multi_polygon_arr = rust_wkb_arr.to_multi_polygon_array()
area = rust_multi_polygon_arr.area()
pa_area_array = pa.array(area)
```
=> Python: separate ffi mod; add primitive arrays

python/core/Cargo.lock, python/core/src/algorithm/geo/area.rs, python/core/src/ffi/from_python.rs, python/core/src/ffi/to_python.rs, python/core/src/lib.rs
This is just a proof of concept, only for area. It's annoying how verbose the implementation is, so I want to ideate on that a bit more.
It works!
```py
import pyarrow as pa
import shapely
import pandas as pd
import geopandas as gpd
from geoarrow.rust.core import WKBArray
gdf = gpd.read_file(gpd.datasets.get_path('nybb'))
large_gdf = pd.concat([gdf] * 1000)
wkb = shapely.to_wkb(large_gdf['geometry'])
pa_wkb_arr = pa.array(wkb)
rust_wkb_arr = WKBArray.from_arrow(pa_wkb_arr)
rust_multi_polygon_arr = rust_wkb_arr.to_multi_polygon_array()
area1 = rust_multi_polygon_arr.area()
from geoarrow.rust.core import area
area2 = area(rust_multi_polygon_arr)
```
Closes https://github.com/geoarrow/geoarrow-rs/issues/266. For https://github.com/geoarrow/geoarrow-python/issues/38
=> python top-level function API

python/core/src/ffi/from_python.rs, python/core/src/ffi/to_python.rs, python/core/src/io/mod.rs, python/core/src/io/wkb.rs, python/core/src/lib.rs, src/array/binary/array.rs, src/io/mod.rs, src/io/wkb/api.rs, src/io/wkb/mod.rs, src/io/wkb/writer/geometry.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/267
This appears to be 2x faster than shapely both at reading and writing WKB
```py
import pyarrow as pa
import shapely
import pandas as pd
import geopandas as gpd
import geoarrow.rust.core
gdf = gpd.read_file(gpd.datasets.get_path("nybb"))
large_gdf = pd.concat([gdf] * 1000)
wkb = shapely.to_wkb(large_gdf["geometry"])
pa_wkb_arr = pa.array(wkb)
%timeit geoarrow.rust.core.from_wkb(pa_wkb_arr)
%timeit shapely.from_wkb(wkb)
geoarrow_arr = geoarrow.rust.core.from_wkb(pa_wkb_arr)
%timeit geoarrow.rust.core.to_wkb(geoarrow_arr)
%timeit shapely.to_wkb(large_gdf["geometry"])
```
=> Implement top-level from/to wkb

src/array/coord/mod.rs, src/array/linestring/builder.rs, src/array/mixed/array.rs, src/array/mixed/builder.rs, src/array/multilinestring/builder.rs, src/array/multipoint/builder.rs, src/array/multipolygon/builder.rs, src/array/point/builder.rs, src/array/polygon/builder.rs, src/io/wkb/api.rs, src/trait_.rs
- Implement conversion of `MixedGeometryArray` to and from `UnionArray`.
- Allow the children of the `MixedGeometryArray` to be `None`
- Remove `point_counter` et al, in favor of `self.points.len()`
- Re-enable previously-failing test, which tested round trip from MixedArray to arrow-rs UnionArray and back.
- Add builder option to prefer adding to multi geometry arrays.
=> Clean up and improve stability of MixedGeometryArray

Cargo.toml, benches/translate.rs, src/algorithm/geo/affine_ops.rs, src/algorithm/geo/scale.rs, src/algorithm/geo/skew.rs, src/algorithm/geo/translate.rs, src/algorithm/proj.rs
Follow up on https://github.com/geoarrow/geoarrow-rs/pull/310#discussion_r1427462729
It's about 20% faster for `translate` when output arrays are pre-allocated:
```
translate PolygonArray  time:   [96.935 µs 97.334 µs 97.805 µs]
change: [-19.186% -18.846% -18.539%] (p = 0.00 < 0.05)
Performance has improved.
```
=> minimize allocations when output geometry arrays are the same size

python/core/src/io/wkb.rs, src/array/binary/array.rs, src/array/geometrycollection/array.rs, src/array/geometrycollection/builder.rs, src/array/mixed/array.rs, src/array/multilinestring/array.rs, src/array/multipoint/array.rs, src/array/multipolygon/array.rs, src/io/wkb/api.rs
- Add `downcast` method to convert to a simpler type. This is relevant for the `Multi*` types, as well as `MixedGeometryArray` and `GeometryCollectionArray` (this should probably go on `GeometryArrayTrait`?)
- Simplify `from_wkb` by parsing to a `GeometryCollectionArray` and then downcasting
=> Implement "downcasting" on arrays to convert to simpler array type

src/array/binary/array.rs, src/array/mixed/builder.rs, src/array/mixed/capacity.rs, src/io/geozero/api/ewkb.rs, src/io/geozero/api/mod.rs, src/io/geozero/api/wkt.rs, src/io/geozero/array/geometrycollection.rs, src/io/geozero/array/linestring.rs, src/io/geozero/array/mixed.rs, src/io/geozero/array/mod.rs, src/io/geozero/array/multilinestring.rs, src/io/geozero/array/multipoint.rs, src/io/geozero/array/multipolygon.rs, src/io/geozero/array/point.rs, src/io/geozero/array/polygon.rs, src/io/geozero/mod.rs
- Add traits for parsing WKT and EWKB to geoarrow via geozero. 
- This is relatively inefficient because it goes through `to_geo` first. In the future we should implement `GeometryCollectionStreamBuilder`
Closes https://github.com/geoarrow/geoarrow-rs/issues/251, closes https://github.com/geoarrow/geoarrow-rs/pull/254.
=> geozero-based wkt and ewkb parsing

Cargo.lock, Cargo.toml, python/core/Cargo.lock, python/core/Cargo.toml, python/core/python/geoarrow/rust/core/rust.pyi, python/core/src/ffi/from_python.rs, python/core/src/table.rs, src/array/mod.rs, src/chunked_array/chunked_array.rs, src/datatypes.rs, src/table/mod.rs
This works now!
```py
from geoarrow.rust.core import GeoTable
from pyogrio.raw import read_arrow
path = '/Users/kyle/github/geoarrow/geoarrow-rs/python/core/ne_10m_roads_north_america/ne_10m_roads_north_america.shp'
meta, table = read_arrow(path)
table = GeoTable.from_arrow(table)
table.geometry
```
=> parse WKB when converting table from arrow

.github/workflows/python-core-wheels.yml
was set to run on the wrong tag
=> fix python-core-wheels ci

js/Cargo.lock, js/Cargo.toml
In order to test `geoparquet-wasm` with recent improvements to downcasting. (fixed here: https://github.com/geoarrow/geoarrow-rs/pull/485/files#diff-2e54e1cdb510a4907fbb46e6f5a8024742517e4368d55e433b608e29d08d4e74R301-R305)
=> bump js version to 0.2.0-beta.2

Cargo.lock, Cargo.toml, src/io/parquet/geoparquet_metadata.rs, src/io/parquet/mod.rs, src/io/parquet/reader.rs, src/io/parquet/reader_async.rs
Implementing an asynchronous GeoParquet file reader using [`ParquetRecordBatchStream`](https://docs.rs/parquet/50.0.0/parquet/arrow/async_reader/struct.ParquetRecordBatchStream.html).
TODO:
Addresses #492
P.S. This is my first ever Rust PR, so take it easy :see_no_evil:
=> Asynchronous geoparquet reader

README.md
Accidentally not removed from https://github.com/geoarrow/geoarrow-rs/pull/495
=> remove accidental edit

src/io/geozero/table/builder/anyvalue.rs, src/io/postgis/reader.rs
Previously we were inferring a string datatype from a datetime column for the next batch. This was erroring whenever we had enough rows for multiple batches.
=> Fix datetime column across multiple batches

.github/workflows/python-core-wheels.yml, python/core/CHANGELOG.md, python/core/Cargo.lock, python/core/Cargo.toml, python/core/src/io/input/sync.rs
- Update with a fix to not implement Fd support on Windows. From https://github.com/omerbenamram/pyo3-file/pull/19.
- Have to wait for redhat to get their shit together: https://status.redhat.com/incidents/qh68rjfg6xs6
- The aarch64 build is failing with ``error: failed to run custom build command for `ring v0.17.8` `` which looks to be https://github.com/briansmith/ring/issues/1414.
=> Fix wheel builds

js/Cargo.lock, js/Cargo.toml, js/src/io/parquet/async.rs, js/src/io/parquet/mod.rs, js/src/io/parquet/options.rs, js/src/io/parquet/sync.rs, python/core/src/io/parquet/mod.rs, python/core/src/io/parquet/options.rs, python/core/src/io/parquet/reader.rs, src/io/parquet/mod.rs, src/io/parquet/reader/async.rs, src/io/parquet/reader/mod.rs, src/io/parquet/reader/options.rs, src/io/parquet/reader/spatial_filter.rs, src/io/parquet/reader/sync.rs
- Refactor `ParquetFile::builder` to consume self, allowing it to be used in `read_geoparquet_async` without requiring a `Clone` bound
- Consolidate `ReadParquetOptions` to cover both the upstream `ArrowReaderOptions` and our own geospatial options.
=> Parquet options updates

js/Cargo.lock, js/Cargo.toml, js/src/io/parquet/async.rs
Directly copied from the equivalent parquet-wasm PR :stuck_out_tongue: .
I'm strongly considering just wrapping [object_store_s3_wasm](https://github.com/JanKaul/object_store_s3_wasm) in object-store-wasm this weekend, so if there's no particular rush, I can work the coveted fsspec-like protocol-differentiated IO into this PR.
Also, one question for any maintainer - `io_parquet_async` implies object-store-wasm::http at a minimum, right? I'm thinking in terms of the other cloud providers, which I imagine would be worth feature-gating at the level of this consuming crate (it's a shame toggling transitive dependency features isn't a thing).
=> Swap AsyncHttpFileReader for HttpObjectStore

js/Cargo.lock, js/Cargo.toml, src/io/parquet/metadata.rs, src/io/parquet/reader/async.rs, src/io/parquet/reader/sync.rs
This is an alternative solution to #609.
One thing we always have to be careful about is ensuring that the schema across record batches is always the same. When the GeoParquet metadata declares the geometry type of the underlying data, we always know what to parse the geometry column to. But it's also allowed for the GeoParquet metadata to not declare the column types. In this case, we parse to a mixed array and then downcast.
But it would be bad to downcast each file of a dataset independently, as it would be possible for one file in a dataset to contain only points and for another to contain only polygons, even where the rest of the schema is the same. 
In this PR, we defer the parsing from WKB until after the data has already been materialized. Maybe this will slightly increase the …
=> Parse Parquet geometry column after reading all files

Cargo.lock, Cargo.toml, js/src/io/parquet/async_file_reader/mod.rs, src/algorithm/geos/buffer.rs, src/algorithm/native/mod.rs, src/array/point/builder.rs, src/array/rect/builder.rs, src/io/geos/array/linestring.rs, src/io/geos/array/multilinestring.rs, src/io/geos/array/multipoint.rs, src/io/geos/array/multipolygon.rs, src/io/geos/array/point.rs, src/io/geos/array/polygon.rs, src/io/geos/scalar/binary.rs, src/io/geos/scalar/coord/combined.rs, src/io/geos/scalar/coord/interleaved.rs, src/io/geos/scalar/coord/mod.rs, src/io/geos/scalar/coord/separated.rs, src/io/geos/scalar/geometry.rs, src/io/geos/scalar/geometrycollection.rs, src/io/geos/scalar/linearring.rs, src/io/geos/scalar/linestring.rs, src/io/geos/scalar/multilinestring.rs, src/io/geos/scalar/multipoint.rs, src/io/geos/scalar/multipolygon.rs, src/io/geos/scalar/point.rs, src/io/geos/scalar/polygon.rs
We can remove a lot of lifetime definitions thanks to https://github.com/georust/geos/pull/153
=> Update geos to 9.0

src/algorithm/native/downcast.rs, src/io/flatgeobuf/writer.rs, src/io/gdal/reader.rs, src/io/geozero/table/data_source.rs, src/lib.rs, src/schema/mod.rs, src/table/mod.rs
Add new `GeoSchemaExt` trait for geospatial operations on arrow schemas
=> Refactor schema operations from table

js/src/io/geojson.rs, python/core/src/ffi/from_python/mod.rs, python/core/src/ffi/from_python/record_batch_reader.rs, python/core/src/ffi/to_python/mod.rs, python/core/src/ffi/to_python/record_batch_reader.rs, python/core/src/io/csv.rs, python/core/src/io/flatgeobuf.rs, python/core/src/io/geojson.rs, python/core/src/io/geojson_lines.rs, python/core/src/io/ipc.rs, python/core/src/lib.rs, python/core/src/stream/mod.rs, src/io/csv/writer.rs, src/io/flatgeobuf/writer.rs, src/io/geojson/writer.rs, src/io/geojson_lines/writer.rs, src/io/geozero/mod.rs, src/io/geozero/table/data_source.rs, src/io/geozero/table/mod.rs, src/io/ipc/writer.rs, src/io/mod.rs, src/io/stream.rs
- Adds Python `RecordBatchReader` class to store a stream of Arrow record batches
- Implements `__arrow_c_stream__` for exporting a Rust stream of record batches to Python
- Implements `FromPyObject` to read from an `__arrow_c_stream__`
- Updates geozero-based writers to read from the stream instead of from a materialized table
- Updates writing Arrow IPC and IPC Stream to not materialize the table
Updating writing GeoParquet from a stream instead of a table is left for future work.
Closes https://github.com/geoarrow/geoarrow-rs/issues/633
=> Implement python record batch reader

src/algorithm/broadcasting/mod.rs, src/algorithm/broadcasting/primitive.rs, src/algorithm/geo/within.rs, src/algorithm/polylabel.rs, src/array/geometrycollection/builder.rs, src/array/metadata.rs, src/array/rect/array.rs, src/io/geojson/geojson_writer.rs, src/io/geozero/mod.rs, src/lib.rs, src/trait_.rs
- Clean up some docs warnings
- Add `#![cfg_attr(docsrs, feature(doc_auto_cfg))]` to `lib.rs` to turn on feature flags in docs.rs, e.g. this from **stac-rs**:
=> Minor doc fixups

.github/workflows/ci.yml, src/io/parquet/mod.rs, src/io/parquet/reader/async.rs, src/io/parquet/reader/mod.rs, src/io/parquet/reader/sync.rs, src/io/parquet/writer/mod.rs
If downstreams want to just depend on a single feature, we need to make sure we can build w/ just that feature enabled ... e.g. as of this writing, `parquet` implicitly depends on `async` but isn't configured as such in `Cargo.toml`.
We can't test w/o installing GDAL and friends because `gdal` is a dev dependency, so we just build.
=> Add CI to build features in isolation

src/array/binary/array.rs, src/array/coord/combined/array.rs, src/array/coord/interleaved/array.rs, src/array/coord/separated/array.rs, src/array/geometrycollection/array.rs, src/array/linestring/array.rs, src/array/metadata.rs, src/array/mixed/array.rs, src/array/mod.rs, src/array/multilinestring/array.rs, src/array/multipoint/array.rs, src/array/multipolygon/array.rs, src/array/point/array.rs, src/array/polygon/array.rs, src/array/rect/array.rs, src/chunked_array/chunked_array.rs, src/error.rs, src/trait_.rs
=> Import from 3d arrayref

src/algorithm/native/binary.rs, src/array/binary/array.rs, src/array/coord/combined/array.rs, src/array/coord/interleaved/array.rs, src/array/coord/separated/array.rs, src/array/geometry/array.rs, src/array/geometrycollection/array.rs, src/array/geometrycollection/builder.rs, src/array/linestring/array.rs, src/array/linestring/builder.rs, src/array/mixed/array.rs, src/array/mixed/builder.rs, src/array/multilinestring/array.rs, src/array/multilinestring/builder.rs, src/array/multipoint/array.rs, src/array/multipoint/builder.rs, src/array/multipolygon/array.rs, src/array/multipolygon/builder.rs, src/array/point/array.rs, src/array/point/builder.rs, src/array/polygon/array.rs, src/array/polygon/builder.rs, src/array/rect/array.rs, src/indexed/array.rs, src/io/geozero/array/mixed.rs, src/trait_.rs
These were a duplicate of `nulls` (in the case of `validity`) or just a simple `cloned` call that wasn't actually used anywhere in the library. By removing these methods, we simplify the API of this crate.
=> Remove `validity` and `logical_nulls` trait methods

src/algorithm/native/downcast.rs, src/array/binary/array.rs, src/array/coord/combined/array.rs, src/array/coord/interleaved/array.rs, src/array/coord/separated/array.rs, src/array/geometrycollection/array.rs, src/array/linestring/array.rs, src/array/mixed/array.rs, src/array/multilinestring/array.rs, src/array/multipoint/array.rs, src/array/multipolygon/array.rs, src/array/point/array.rs, src/array/polygon/array.rs, src/array/rect/array.rs, src/chunked_array/chunked_array.rs, src/datatypes.rs, src/indexed/array.rs, src/trait_.rs
`GeoDataType` is `Copy`, so it's cheap to return as-is. This also aligns it to be a similar return to `GeometryArrayTrait::storage_type`.
This was prompted by seeing the following method in `Downcast`:
```rust
fn downcasted_data_type(&self, small_offsets: bool) -> GeoDataType {
*self.data_type()
}
```
This felt a little funny from an interface perspective — to me, it feels more natural to always return a `GeoDataType` instead of a `&`-ref in some places but not others.
If there's ever a future case where `GeoDataType` _won't_ be `Copy`, then this PR is a bad idea and should be rejected 🙇🏼.
=> Return the GeoDataType, not a ref

Cargo.lock, Cargo.toml, js/Cargo.lock, js/Cargo.toml, src/algorithm/mod.rs, src/lib.rs
This adds `#![deny(unused_crate_dependencies)]` to `lib.rs` and then does the cleanups required. Lets us drop a couple of dependencies altogether, and move a couple others to optional.
=> Deny unused crates

.github/workflows/ci.yml, .github/workflows/python.yml, .github/workflows/wasm.yml
- Closes #697 
I ended up touching the wasm and python workflows as well, mostly to make whitespace consistent and to remove the `--all` flags from the `cargo` commands (only used for workspaces, and its deprecated).
=> Simplify some CI checks

python/core/python/geoarrow/rust/core/_rust.pyi, python/core/src/io/parquet/reader.rs
Expose the schema before reading any of the actual data.
=> Python, GeoParquet: expose `schema_arrow` attribute on ParquetFile and ParquetDataset

Cargo.toml, js/Cargo.toml, python/core/Cargo.toml
I'm not sure what recent rust feature I'm using, but @bonkles was unable to compile the JS bindings on rust 1.77
=> Bump msrv to 1.80

CHANGELOG.md, Cargo.lock, Cargo.toml, python/core/Cargo.lock, python/core/Cargo.toml
If it's ok, I'd be stoked to get a v0.3.0 release of **geoarrow** — some of my **stac-geoparquet** is getting close to being release-able.
Here's a checklist of things that have been mentioned as part of a v0.3 (including https://github.com/geoarrow/geoarrow-rs/issues/628#issuecomment-2282304182 and https://github.com/geoarrow/geoarrow-rs/milestone/3):
- #660 is done ✅ 
- Some (but not all) of the doc updates are done in https://github.com/geoarrow/geoarrow-rs/pull/696, and I've got a tracking issue for the rest in https://github.com/geoarrow/geoarrow-rs/issues/689
- "Broader support for 3d geometries" isn't done as far as I know, but I haven't really been touching that at all yet
- https://github.com/geoarrow/geoarrow-rs/issues/539 is a Python thing, not a Rust crate thing
As a part of …
=> Release geoarrow v0.3.0-beta.1

CHANGELOG.md, Cargo.lock, Cargo.toml
Hoping to fix docs.rs builds.
- Closes #706
=> Relax geos to v3.10.0, bump geoarrow to v0.3.0-beta.2

src/algorithm/native/cast.rs, src/algorithm/native/downcast.rs, src/array/mixed/array.rs, src/array/mixed/builder.rs, src/datatypes.rs, src/io/parquet/test.rs
- Fix DataType creation to match the spec, with hard-coded type ids.
- Don't include geoarrow metadata on underlying arrays when exporting to arrow-rs. Only include geoarrow metadata on top-level `geoarrow.geometry` array
- We no longer need a `map` attribute in the struct because the ordering of the fields is guaranteed by the spec now.
- Don't store underlying arrays under an `Option`
Closes https://github.com/geoarrow/geoarrow-rs/pull/717, closes https://github.com/geoarrow/geoarrow-rs/pull/714
Unblocks https://github.com/geoarrow/geoarrow-rs/pull/646
Progress towards https://github.com/geoarrow/geoarrow-rs/issues/679
=> Fix union array interop

src/algorithm/native/eq.rs, src/io/geo/scalar.rs, src/io/geos/array/binary.rs, src/io/geos/array/geometrycollection.rs, src/io/geos/array/mixed.rs, src/io/geos/array/mod.rs, src/io/geos/scalar/binary.rs, src/io/geos/scalar/coord/interleaved.rs, src/io/geos/scalar/coord/separated.rs, src/io/geos/scalar/geometry.rs, src/io/geos/scalar/geometrycollection.rs, src/io/geos/scalar/linestring.rs, src/io/geos/scalar/mod.rs, src/io/geos/scalar/multilinestring.rs, src/io/geos/scalar/multipoint.rs, src/io/geos/scalar/multipolygon.rs, src/io/geos/scalar/point.rs, src/io/geos/scalar/polygon.rs
- Support 3d coordinates in geometry equality
- Support converting GEOS geometries to WKBArray, MixedGeometryArray, and ~~GeometryCollectionArray~~
- Support 3d coordinates in converting GeoArrow data to GEOS
- New GEOSGeometry and GEOSGeometryCollection structs, which can have GeometryTrait and GeometryCollectionTrait implemented on them.
Future work: 
- The geos `get_geometry_n` function returns a `ConstGeometry`, so we'd need a second set of structs to implement GeometryCollectionTrait on that
For https://github.com/geoarrow/geoarrow-rs/issues/662
=> Support z values in GEOS round trip

python/core/Cargo.lock, python/core/Cargo.toml, python/core/poetry.lock, python/core/pyproject.toml, python/core/python/geoarrow/rust/core/_rust.pyi, python/core/src/error.rs, python/core/src/io/parquet/reader.rs, python/core/tests/io/test_geoparquet.py
It turns out that CRS is indeed maintained when reading/writing GeoParquet, but that `from_geopandas` separately loses CRS
=> Add CRS tests for writing/reading GeoParquet

js/Cargo.lock, js/src/algorithm/geoarrow/coord_format.rs, src/algorithm/native/cast.rs, src/algorithm/native/downcast.rs, src/algorithm/native/mod.rs, src/array/coord/separated/array.rs, src/array/geometrycollection/array.rs, src/array/linestring/array.rs, src/array/mixed/array.rs, src/array/multilinestring/array.rs, src/array/multipoint/array.rs, src/array/multipolygon/array.rs, src/array/point/array.rs, src/array/polygon/array.rs, src/array/util.rs
- Don't use builders for simple casts (this should be faster)
- Direct `From` and `TryFrom` implementations
=> Cleaner casting

src/io/wkb/mod.rs
This makes `get_wkb_geometry_type` usable.
=> Make `WKBType` public

Cargo.lock, Cargo.toml, python/Cargo.lock, python/geoarrow-core/src/interop/wkt.rs, src/io/mod.rs, src/io/wkt/mod.rs, src/io/wkt/reader/mod.rs, src/io/wkt/reader/wkt_trait.rs
- Depend on `wkt` directly (note that this means we now have two copies of `wkt` in our dependency tree, since `geos` apparently depends on `wkt 0.10.3`.
- Implement `geo-traits` traits on `wkt` types objects.
- Initial start of new `ParseWKT` trait that parses a WKT string array without using our streaming builder. I think it'll be better in the long run to minimize the use of the streaming builder.
Testing from Python, it looks like this may be minimally faster than the previous streaming implementation:
```py
import pyarrow as pa
import geopandas as gpd
import shapely
from geoarrow.rust.core import from_wkt
path = "/Users/kyle/Downloads/nz-building-outlines.parquet"
gdf = gpd.read_parquet(path)
wkt_arr = shapely.to_wkt(gdf.geometry.array)
pa_wkt_arr = pa.array(wkt_arr[:100_000]) …
```
=> Use geo-traits for parsing WKT

src/io/wkt/mod.rs, src/io/wkt/writer/mod.rs, src/io/wkt/writer/scalar.rs
- Convert geo-traits scalars to `wkt::Wkt`
- This is prep work for direct transformation of geoarrow scalars to `wkt::Wkt` objects.
- This does not go through geozero, partially because I hit issues with multidimensional writing in https://github.com/georust/geozero/pull/237
- This supersedes https://github.com/geoarrow/geoarrow-rs/pull/788, though it hasn't yet piped through to a full `ToWkt` trait implemented on arrays. cc @b4l
In the future, hopefully geo-traits will be standardized and we'll be able to pass trait objects directly to `wkt`'s APIs
For https://github.com/geoarrow/geoarrow-rs/issues/762
=> Prep work for to_wkt

Cargo.lock, Cargo.toml, python/Cargo.lock, python/Cargo.toml, python/pyo3-geoarrow/Cargo.toml
Set versions so we can publish to crates.io
I'm not sure how I want to version this. Should I version it separately? With the core `geoarrow` crate?
=> Set pyo3-geoarrow to 0.1.0-beta.1

python/geoarrow-compute/pyproject.toml, python/geoarrow-core/pyproject.toml, python/geoarrow-core/python/geoarrow/rust/core/_constructors.pyi, python/geoarrow-core/python/geoarrow/rust/core/_rust.pyi, python/geoarrow-core/src/constructors.rs, python/geoarrow-core/src/lib.rs, python/geoarrow-io/pyproject.toml, python/pyo3-geoarrow/src/coord_buffer.rs, python/pyo3-geoarrow/src/lib.rs, python/pyo3-geoarrow/src/offset_buffer.rs, python/tests/core/test_constructors.py
- Add `PyCoordBuffer` and `PyOffsetBuffer` to pyo3-geoarrow wrapping the `CoordBuffer` and `OffsetBuffer` concepts from geoarrow.
- Add `points`, `linestrings`, `polygons`, `multipoints`, `multilinestrings`, `multipolygons` constructor functions
- Bump dependency to arro3-core 0.4 or higher
- Simple constructor tests for points and linestrings.
=> Python geometry array constructors

python/docs/api/core/constructors.md, python/mkdocs.yml
Follow up from https://github.com/geoarrow/geoarrow-rs/pull/810
=> Add python constructors to docs

src/algorithm/native/map_coords.rs, src/algorithm/native/take.rs, src/array/geometrycollection/builder.rs, src/array/linestring/builder.rs, src/array/mixed/builder.rs, src/array/mixed/mod.rs, src/array/multilinestring/builder.rs, src/array/multipoint/builder.rs, src/array/multipolygon/builder.rs, src/array/point/builder.rs, src/array/polygon/builder.rs, src/datatypes.rs, src/io/geozero/api/ewkb.rs, src/io/geozero/api/wkt.rs, src/io/geozero/array/mixed.rs, src/io/parquet/test.rs, src/io/wkt/reader/mod.rs, src/trait_.rs
- Move `prefer_multi` from a parameter when adding a single geometry to a parameter on builder initialization. Realistically, the `prefer_multi` keyword is used when downcasting is planned, such as when using an unknown geometry source. In these cases, we'll always know on array creation whether we'll want to downcast later.
- This means that we can now add `push_geometry` onto the `GeometryArrayBuilder` trait, because we have a single signature that all builders can follow. This should make it a lot easier to manage stuff like macros because we won't need a different impl for points, geometries, and geometry collections.
=> Add `push_geometry` to `GeometryArrayBuilder`

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, js/Cargo.lock, js/Cargo.toml, python/Cargo.lock, python/Cargo.toml, python/geoarrow-compute/Cargo.toml, python/geoarrow-core/Cargo.toml, python/geoarrow-io/Cargo.toml, python/geoarrow-io/python/geoarrow/rust/io/_io.pyi, python/geoarrow-io/src/io/mod.rs, python/geoarrow-io/src/io/shapefile.rs, python/geoarrow-io/src/lib.rs, python/pyo3-geoarrow/Cargo.toml, python/tests/io/test_shapefile.py, src/error.rs, src/io/flatgeobuf/reader/sync.rs, src/io/geozero/table/builder/anyvalue.rs, src/io/geozero/table/builder/mod.rs, src/io/geozero/table/builder/properties.rs, src/io/geozero/table/builder/table.rs, src/io/geozero/table/mod.rs, src/io/mod.rs, src/io/shapefile/mod.rs, src/io/shapefile/reader.rs, src/io/shapefile/scalar.rs, src/lib.rs, src/table.rs
- Add `read_shapefile` function to Rust
- Add bare-bones `read_shapefile` function to Python, which currently makes you supply paths for both the SHP and DBF paths.
- Add `Date32` variant to `AnyBuilder`.
- Remove geozero feature flag (always include the base geozero dependency)
Todo:
Looks pretty good!!
=> Add shapefile reader

.github/workflows/python-docs.yml, python/Cargo.lock, python/Cargo.toml
Ref https://github.com/developmentseed/obstore/pull/86
=> Python: Publish beta version docs as non-latest

rust/geoarrow/src/algorithm/native/map_coords.rs, rust/geoarrow/src/scalar/point/scalar.rs, rust/geoarrow/src/trait_.rs
This forces the use of `PointTrait::coord`, which returns `Option<Coord>`, which is `None` if the point is empty.
Closes https://github.com/geoarrow/geoarrow-rs/issues/840
=> Remove infallible accessor for `Point::coord`

Cargo.lock, rust/geoarrow/Cargo.toml
No longer use git dependencies for these two now that the latest versions have been published.
=> Use released wkt and wkb

rust/geoarrow/src/array/unknown/builder.rs, rust/geoarrow/src/trait_.rs
Adding nulls is tricky. We often want to use this builder as a generic builder for data
from unknown sources, which then gets downcasted to an array of a specific type.
In a large majority of the time, this builder will have only data of a single type, which
can then get downcasted to a simple array of a single geometry type and dimension. But in
order for this process to be easy, we want the nulls to be assigned to the same array type
as the actual data.
When there's a valid geometry pushed before the null, we can add the null to an existing
non-null array type, but if there are no valid geometries yet, we don't know which array to
push the null to. This `deferred_nulls` is the number of initial null values that haven't
yet been written to an array, because we don't know which array to …
=> handle `push_null` in the unknown geometry builder

rust/geoarrow/src/array/geometry/array.rs, rust/geoarrow/src/array/mixed/array.rs
It turns out we actually didn't need a slice_offset
=> Simplify mixed slicing

rust/geoarrow/src/algorithm/geos/bool_ops.rs, rust/geoarrow/src/algorithm/geos/mod.rs, rust/geoarrow/src/algorithm/native/binary.rs, rust/geoarrow/src/algorithm/native/unary.rs, rust/geoarrow/src/io/geos/scalar/coord/combined.rs, rust/geoarrow/src/io/geos/scalar/coord/mod.rs, rust/geoarrow/src/io/geos/scalar/geometry.rs, rust/geoarrow/src/io/geos/scalar/geometrycollection.rs, rust/geoarrow/src/io/geos/scalar/linestring.rs, rust/geoarrow/src/io/geos/scalar/mod.rs, rust/geoarrow/src/io/geos/scalar/multilinestring.rs, rust/geoarrow/src/io/geos/scalar/multipoint.rs, rust/geoarrow/src/io/geos/scalar/multipolygon.rs, rust/geoarrow/src/io/geos/scalar/point.rs, rust/geoarrow/src/io/geos/scalar/polygon.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/440
=> Implement geos bool ops

rust/geoarrow/src/algorithm/native/cast.rs, rust/geoarrow/src/algorithm/native/downcast.rs, rust/geoarrow/src/array/geometry/array.rs, rust/geoarrow/src/array/linestring/array.rs, rust/geoarrow/src/array/mixed/array.rs, rust/geoarrow/src/array/multilinestring/array.rs, rust/geoarrow/src/array/multipoint/array.rs, rust/geoarrow/src/array/multipolygon/array.rs, rust/geoarrow/src/array/point/array.rs, rust/geoarrow/src/array/polygon/array.rs, rust/geoarrow/src/datatypes.rs, rust/geoarrow/src/io/wkb/api.rs, rust/geoarrow/src/table.rs
todo:
Closes https://github.com/geoarrow/geoarrow-rs/issues/416
=> downcast geometry array

Cargo.lock, rust/geoarrow/Cargo.toml
Should fix a memory leak in GEOS bindings.
Closes https://github.com/geoarrow/geoarrow-rs/issues/936, ref https://github.com/georust/geos/issues/160#issuecomment-2516122859
=> bump geos to 9.1.1

.github/workflows/ci.yml, Cargo.lock, rust/geodatafusion/Cargo.toml, rust/geodatafusion/src/udf/native/accessors/coord_dim.rs, rust/geodatafusion/src/udf/native/accessors/envelope.rs, rust/geodatafusion/src/udf/native/accessors/line_string.rs, rust/geodatafusion/src/udf/native/bounding_box/box.rs, rust/geodatafusion/src/udf/native/bounding_box/extrema.rs, rust/geodatafusion/src/udf/native/constructors/point.rs, rust/geodatafusion/src/udf/native/io/mod.rs, rust/geodatafusion/src/udf/native/io/union_example.rs, rust/geodatafusion/src/udf/native/io/wkb.rs, rust/geodatafusion/src/udf/native/io/wkt.rs, rust/geodatafusion/src/udf/native/measurement/area.rs, rust/geodatafusion/src/udf/native/mod.rs, rust/geodatafusion/src/udf/native/processing/centroid.rs, rust/geodatafusion/src/udf/native/processing/chaikin_smoothing.rs, rust/geodatafusion/src/udf/native/processing/convex_hull.rs, rust/geodatafusion/src/udf/native/processing/mod.rs
Uses latest datafusion main in an attempt to solve https://github.com/apache/datafusion/issues/13762. 
The example in https://github.com/apache/datafusion/issues/13762 is still failing (the tests added in this branch were switched to using `unwrap_err()` instead of `unwrap()`).
I'll still merge this PR because there are other breaking changes in the upcoming release of datafusion, and I'd like to make other PRs here that use the latest API.
=> Update to latest datafusion main

.github/workflows/ci.yml, .github/workflows/python-core-wheels.yml, .github/workflows/python-io-wheels.yml, python/DEVELOP.md, python/geoarrow-core/DEVELOP.md, rust/geoarrow/src/algorithm/geo/contains.rs, rust/geoarrow/src/algorithm/geo/intersects.rs, rust/geoarrow/src/io/geo.rs, rust/geoarrow/src/io/mod.rs, rust/geoarrow/src/scalar/binary/scalar.rs, rust/geoarrow/src/scalar/geometry/scalar.rs, rust/geoarrow/src/scalar/geometrycollection/scalar.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/716. Ref https://github.com/georust/geo/pull/1255#issuecomment-2557320731.
Note that this is the same underlying implementation as upstream geo in <https://github.com/georust/geo/pull/1255>. However, the trait-based implementation hits this compiler regression <https://github.com/rust-lang/rust/issues/128887>, <https://github.com/rust-lang/rust/issues/131960>, which prevents from compiling in release mode on a stable Rust version. For some reason, the **function-based implementation** does not hit this regression, and thus allows building geoarrow without using latest nightly and a custom `RUSTFLAGS`.
Note that it's only `GeometryTrait` and `GeometryCollectionTrait` that hit this compiler bug.
Other traits can use the upstream impls.
=> Work around upstream compiler bug

python/tests/interop/test_wkb.py, rust/geoarrow/src/array/geometry/array.rs, rust/geoarrow/src/datatypes.rs, rust/geoarrow/src/io/csv/mod.rs, rust/geoarrow/src/io/csv/reader.rs, rust/geoarrow/src/io/csv/writer.rs, rust/geoarrow/src/io/flatgeobuf/reader/async.rs, rust/geoarrow/src/io/flatgeobuf/writer.rs, rust/geoarrow/src/io/geos/array/binary.rs, rust/geoarrow/src/io/geos/array/linestring.rs, rust/geoarrow/src/io/geos/array/multilinestring.rs, rust/geoarrow/src/io/geos/array/multipoint.rs, rust/geoarrow/src/io/geos/array/multipolygon.rs, rust/geoarrow/src/io/geos/array/point.rs, rust/geoarrow/src/io/geos/array/polygon.rs, rust/geoarrow/src/io/geos/scalar/linestring.rs, rust/geoarrow/src/io/geozero/scalar/geometry.rs, rust/geoarrow/src/io/geozero/table/data_source.rs, rust/geoarrow/src/io/ipc/writer.rs, rust/geoarrow/src/io/mod.rs, rust/geoarrow/src/io/postgis/reader.rs, rust/geoarrow/src/io/shapefile/reader.rs, rust/geoarrow/src/io/stream.rs, rust/geoarrow/src/io/wkb/api.rs, rust/geoarrow/src/io/wkb/writer/mod.rs, rust/geoarrow/src/io/wkb/writer/rect.rs
- Simplify implementation of `RecordBatchReader` wrapper.
- Deny missing documentation in `geoarrow::io`.
- Implement writing a `RectArray` to a `WKBArray`
- Update `FromWKB` to impl for `GeometryArray`. 
- Use the `GeometryArray` impl for the `dyn NativeArray` impl.
- Fix `GeometryArray` FFI. We hadn't been correctly exporting the underlying GeometryCollection array.
=> Improve docs for `geoarrow::io` module & GeometryArray FFI fix

python/Cargo.lock, python/geoarrow-io/src/io/parquet/async.rs, python/geoarrow-io/src/io/parquet/sync.rs, python/pyo3-geoarrow/src/array.rs, python/pyo3-geoarrow/src/chunked_array.rs, python/pyo3-geoarrow/src/data_type.rs, python/pyo3-geoarrow/src/scalar.rs
- Add the [`frozen`](https://pyo3.rs/v0.23.3/class.html?highlight=frozen#frozen-classes-opting-out-of-interior-mutability) attribute to `#[pyclass]`. This should be a small performance improvement, and allows for accessing the interior of a class even without the GIL.
Ref https://github.com/developmentseed/obstore/pull/118
=> frozen pyclasses

rust/geoarrow/src/algorithm/geo/bounding_rect.rs, rust/geoarrow/src/scalar/geometrycollection/scalar.rs
As described in a contained comment:
We can't implement both
```
impl From<GeometryCollection<'_>> for geo::GeometryCollection
```
and
```
impl From<GeometryCollection<'_>> for geo::Geometry
```
because of this problematic blanket impl
(https://github.com/georust/geo/blob/ef55eabe9029b27f753d4c40db9f656e3670202e/geo-types/src/geometry/geometry_collection.rs#L113-L120).
Thus we need to choose either one or the other to implement.
If we implemented only `for geo::Geometry`, then the default blanket impl for
`geo::GeometryCollection` would be **wrong** because it would doubly-nest the
`GeometryCollection`:
```rs
GeometryCollection(
[
GeometryCollection(
GeometryCollection(
[
Point(
Point(
Coord {
x: 0.0,
y: 0.0,
},
),
),
],
),
),
],
)
```
Therefore we must implement only `for …
=> Fix stack overflow when converting `GeometryCollection` scalar to geo

rust/geoarrow/src/datatypes.rs
The spec says the fields should be named: https://github.com/geoarrow/geoarrow/blob/dd06406d11f2a498b70b6c74f0deda62ec79067b/format.md#geometry
cc @paleolimbot 
ref https://github.com/geoarrow/geoarrow-python/issues/60
=> Fix geometry field names when exporting to Arrow

Cargo.lock, rust/geoarrow/Cargo.toml
GEOS v9 was yanked. We can't run `cargo update` until we bump GEOS to `10`
=> Bump GEOS to 10

Cargo.lock, python/Cargo.lock, python/Cargo.toml, rust/geoarrow/Cargo.toml
Not sure if you always release python at the same time, but I just searched for `0.4.0-beta.3` and updated all of those. This will unblock some dev over at **stac-rs** where I'd like to get onto arrow 54.
=> release: v0.4.0-beta.4

rust/geoarrow/Cargo.toml, rust/geoarrow/src/io/parquet/writer/async.rs
- Updates the trait bound used by the AsyncGeoParquetWriter's inner writer with the upstream Arrow's AsyncFileWriter trait introduced in Arrow 52.0.0
- This update allows the use of the ParquetObjectWriter introduced in Arrow 53.0.0
=> Updates AsyncGeoParquetWriter's inner writer trait bound

Cargo.lock, Cargo.toml, rust/geoarrow-schema/Cargo.toml, rust/geoarrow-schema/README.md, rust/geoarrow-schema/src/coord_type.rs, rust/geoarrow-schema/src/crs.rs, rust/geoarrow-schema/src/dimension.rs, rust/geoarrow-schema/src/edges.rs, rust/geoarrow-schema/src/lib.rs, rust/geoarrow-schema/src/metadata.rs, rust/geoarrow-schema/src/type.rs, rust/geoarrow/src/array/metadata.rs
- Add new `geoarrow_schema` crate
- Move `CoordType`, `Dimension`, `Crs`, `Edges`, `Metadata`, to new crate.
- Add tests for metadata serialization and deserialization
- Add new geometry-type-specific structs: BoxType, GeometryCollectionType, GeometryType, LineStringType, MultiLineStringType, MultiPointType, MultiPolygonType, PointType, PolygonType, WkbType, WktType
- Implement the upstream [`ExtensionType`](https://docs.rs/arrow-schema/latest/arrow_schema/extension/trait.ExtensionType.html) trait for each of these new structs.
Closes https://github.com/geoarrow/geoarrow-rs/issues/987
cc @paleolimbot 
Will probably leave for future PRs integrating this into existing `geoarrow` code because it'll require changing our current use of `NativeType` (see #1016 draft)
=> geoarrow-schema crate, plus implementation of upstream ExtensionType trait

rust/geoarrow-array/src/array/geometry.rs, rust/geoarrow-array/src/array/geometrycollection.rs, rust/geoarrow-array/src/array/linestring.rs, rust/geoarrow-array/src/array/mixed.rs, rust/geoarrow-array/src/array/multilinestring.rs, rust/geoarrow-array/src/array/multipoint.rs, rust/geoarrow-array/src/array/multipolygon.rs, rust/geoarrow-array/src/array/point.rs, rust/geoarrow-array/src/array/polygon.rs, rust/geoarrow-array/src/array/rect.rs, rust/geoarrow-array/src/array/wkb.rs, rust/geoarrow-array/src/builder/geometry.rs, rust/geoarrow-array/src/builder/geometrycollection.rs, rust/geoarrow-array/src/builder/linestring.rs, rust/geoarrow-array/src/builder/mixed.rs, rust/geoarrow-array/src/builder/multilinestring.rs, rust/geoarrow-array/src/builder/multipoint.rs, rust/geoarrow-array/src/builder/multipolygon.rs, rust/geoarrow-array/src/builder/point.rs, rust/geoarrow-array/src/builder/polygon.rs, rust/geoarrow-array/src/builder/rect.rs, rust/geoarrow-array/src/builder/wkb.rs, rust/geoarrow-array/src/scalar/multilinestring.rs, rust/geoarrow-array/src/test/linestring.rs, rust/geoarrow-array/src/test/multilinestring.rs, rust/geoarrow-array/src/test/multipoint.rs, rust/geoarrow-array/src/test/multipolygon.rs, rust/geoarrow-array/src/test/point.rs, rust/geoarrow-array/src/test/polygon.rs
So instead of both `new` and `new_with_options`
```rs
// OLD
impl LineStringBuilder {
/// Creates a new empty [`LineStringBuilder`].
pub fn new(dim: Dimension) -> Self;
/// Creates a new empty [`LineStringBuilder`] with the provided options.
pub fn new_with_options(
dim: Dimension,
coord_type: CoordType,
metadata: Arc<Metadata>,
) -> Self;
```
we now just have a `new` that takes in a relevant type
```rs
// NEW
impl LineStringBuilder {
/// Creates a new empty [`LineStringBuilder`].
pub fn new(typ: LineStringType) -> Self;
```
And similarly, instead of having with `with_capacity` and `with_capacity_with_options`, we now have just `with_capacity`.
This also simplifies the signature of APIs like
```rs
pub fn from_line_strings(
geoms: &[impl LineStringTrait<T = f64>],
dim: Dimension, …
```
=> Simplify builder apis

rust/geoarrow-array/src/cast.rs
I'm tired today and accidentally pushed to main in https://github.com/geoarrow/geoarrow-rs/commit/80e905b1086deb357ca69819b5740ebacc269714. (github branch protection settings are so weird. I can't push with `--force`, but I _can_ push without `--force`. I since turned on "do not allow bypassing these settings", which might help prevent this again in the future)
Then https://github.com/geoarrow/geoarrow-rs/pull/1030 auto-merged on top of it and I decided it wasn't worth the work to rewrite the history. This PR fixes the doctest from https://github.com/geoarrow/geoarrow-rs/commit/80e905b1086deb357ca69819b5740ebacc269714
=> Add `downcast_geometry_array` macro

rust/geoarrow-array/src/array/geometry.rs, rust/geoarrow-array/src/array/geometrycollection.rs, rust/geoarrow-array/src/array/linestring.rs, rust/geoarrow-array/src/array/mixed.rs, rust/geoarrow-array/src/array/mod.rs, rust/geoarrow-array/src/array/multilinestring.rs, rust/geoarrow-array/src/array/multipoint.rs, rust/geoarrow-array/src/array/multipolygon.rs, rust/geoarrow-array/src/array/polygon.rs, rust/geoarrow-array/src/array/wkb.rs, rust/geoarrow-array/src/array/wkt.rs, rust/geoarrow-array/src/builder/geometry.rs, rust/geoarrow-array/src/builder/geometrycollection.rs, rust/geoarrow-array/src/builder/linestring.rs, rust/geoarrow-array/src/builder/mixed.rs, rust/geoarrow-array/src/builder/multilinestring.rs, rust/geoarrow-array/src/builder/multipoint.rs, rust/geoarrow-array/src/builder/multipolygon.rs, rust/geoarrow-array/src/builder/point.rs, rust/geoarrow-array/src/builder/polygon.rs, rust/geoarrow-array/src/builder/wkb.rs, rust/geoarrow-array/src/capacity/wkb.rs, rust/geoarrow-array/src/cast.rs, rust/geoarrow-array/src/datatypes.rs, rust/geoarrow-array/src/scalar/mod.rs, rust/geoarrow-array/src/trait_.rs
Changes list
- Rename `WKBArray` to `WkbArray` and `WKTArray` to `WktArray`
- Rename `GeoArrowType` enum variants `WKB` to `Wkb` and `WKT` to `Wkt`
This makes it consistent with other naming:
- `wkb::reader::Wkb`
- `wkt::Wkt`
- `geoarrow_schema::WkbType`
- `geoarrow_schema::WktType`
=> Rename `WKBArray` to `WkbArray` and `WKTArray` to `WktArray`

rust/geoarrow-array/src/array/geometry.rs, rust/geoarrow-array/src/array/geometrycollection.rs, rust/geoarrow-array/src/array/linestring.rs, rust/geoarrow-array/src/array/mixed.rs, rust/geoarrow-array/src/array/multilinestring.rs, rust/geoarrow-array/src/array/multipoint.rs, rust/geoarrow-array/src/array/multipolygon.rs, rust/geoarrow-array/src/array/point.rs, rust/geoarrow-array/src/array/polygon.rs, rust/geoarrow-array/src/array/rect.rs, rust/geoarrow-array/src/array/wkb.rs, rust/geoarrow-array/src/array/wkt.rs, rust/geoarrow-array/src/trait_.rs, rust/geoarrow-schema/README.md, rust/geoarrow-schema/src/coord_type.rs, rust/geoarrow-schema/src/crs.rs, rust/geoarrow-schema/src/edges.rs, rust/geoarrow-schema/src/lib.rs, rust/geoarrow-schema/src/metadata.rs, rust/geoarrow-schema/src/type.rs, rust/geoarrow/src/io/parquet/writer/metadata.rs
- Adds `#![warn(missing_docs)]` to `geoarrow_schema`.
- Updated to latest `Edges` variants
- Some drive by docs cleanups
=> Updated `geoarrow_schema` crate documentation

rust/geoarrow-array/src/array/geometry.rs, rust/geoarrow-array/src/array/geometrycollection.rs, rust/geoarrow-array/src/array/linestring.rs, rust/geoarrow-array/src/array/mixed.rs, rust/geoarrow-array/src/array/multilinestring.rs, rust/geoarrow-array/src/array/multipoint.rs, rust/geoarrow-array/src/array/multipolygon.rs, rust/geoarrow-array/src/array/point.rs, rust/geoarrow-array/src/array/polygon.rs, rust/geoarrow-array/src/array/rect.rs, rust/geoarrow-array/src/datatypes.rs, rust/geoarrow-array/src/scalar/coord/combined.rs, rust/geoarrow-array/src/scalar/specialization.rs, rust/geoarrow-array/src/test/linestring.rs, rust/geoarrow-array/src/test/mod.rs, rust/geoarrow-array/src/test/multilinestring.rs, rust/geoarrow-array/src/test/multipoint.rs, rust/geoarrow-array/src/test/multipolygon.rs, rust/geoarrow-array/src/test/point.rs, rust/geoarrow-array/src/test/polygon.rs, rust/geoarrow-array/src/test/rect.rs
- Adds tests for both interleaved and separated encoding to go from geo to geoarrow and back to geo and assert equality
- Adds tests for both interleaved and separated encoding to go from geoarrow to arrow and back
- Adds minimal `PartialEq` tests
=> Add round trip `geo` and `arrow` tests for each array type

Cargo.lock, Cargo.toml, js/Cargo.lock, js/Cargo.toml, js/src/io/parquet/async.rs, js/src/io/parquet/async_file_reader/fetch.rs, js/src/io/parquet/async_file_reader/mod.rs, python/Cargo.lock, python/Cargo.toml, python/geoarrow-io/Cargo.toml, python/geoarrow-io/src/io/parquet/async.rs, python/geoarrow-io/src/io/parquet/sync.rs, rust/geoarrow/Cargo.toml, rust/geoarrow/src/io/flatgeobuf/reader/object_store_reader.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/1037
- Bump `arrow` to `55` and `parquet` to `55`
- Temporarily deactivates the `datafusion` integration until datafusion publishes its version `47` (https://github.com/apache/datafusion/issues/15072), so that we can progress with the `arrow` 55 upgrade now.
- Update JS and Python APIs for latest `parquet`. 
- Means we no longer need an initial `HEAD` request for Parquet files before reading metadata.
=> Bump arrow to 55

rust/geoarrow-array/src/error.rs, rust/geoarrow/src/error.rs, rust/geoarrow/src/io/flatgeobuf/reader/sync.rs, rust/geoarrow/src/io/parquet/reader/spatial_filter.rs
Closes #1039 
Many APIs where we pass in a callback into the Arrow crate require the returned error type to be ArrowError, so implementing this `From` makes the conversion less verbose there.
=> Implement From<GeoArrowError> for ArrowError

Cargo.lock, Cargo.toml, rust/geoarrow-test/Cargo.toml, rust/geoarrow-test/README.md, rust/geoarrow-test/src/geometry.rs, rust/geoarrow-test/src/geometrycollection.rs, rust/geoarrow-test/src/lib.rs, rust/geoarrow-test/src/linestring.rs, rust/geoarrow-test/src/multilinestring.rs, rust/geoarrow-test/src/multipoint.rs, rust/geoarrow-test/src/multipolygon.rs, rust/geoarrow-test/src/point.rs, rust/geoarrow-test/src/polygon.rs, rust/geoarrow-test/src/raw/geometry.rs, rust/geoarrow-test/src/raw/geometrycollection.rs, rust/geoarrow-test/src/raw/linestring.rs, rust/geoarrow-test/src/raw/mod.rs, rust/geoarrow-test/src/raw/multilinestring.rs, rust/geoarrow-test/src/raw/multipoint.rs, rust/geoarrow-test/src/raw/multipolygon.rs, rust/geoarrow-test/src/raw/point.rs, rust/geoarrow-test/src/raw/polygon.rs
- Includes copied in data from https://github.com/geoarrow/geoarrow-data/blob/3feaaa0b56758e2b5d7afc1c44c6555cb589d295/example/example_src.yaml and https://github.com/geoarrow/geoarrow-data/blob/3feaaa0b56758e2b5d7afc1c44c6555cb589d295/example/example_src_generated.yaml. By copying in the data, we can pass the WKT strings to the `wkt!` macro (https://github.com/georust/wkt/pull/137)
- It includes all geometry types except for `geometrycollection-nested`, which we leave for the future.
- This PR just defines the test data; it doesn't add it to any tests yet.
cc @paleolimbot
=> Add `geoarrow-test` subcrate with WKT data from geoarrow-data

rust/geoarrow-array/src/array/geometry.rs, rust/geoarrow-array/src/array/geometrycollection.rs, rust/geoarrow-array/src/array/linestring.rs, rust/geoarrow-array/src/array/mixed.rs, rust/geoarrow-array/src/array/multilinestring.rs, rust/geoarrow-array/src/array/multipoint.rs, rust/geoarrow-array/src/array/multipolygon.rs, rust/geoarrow-array/src/array/point.rs, rust/geoarrow-array/src/array/polygon.rs
- Add `into_coord_type` to all native geoarrow array types that can have multiple coordinate types (excluding Rect, Wkt, Wkb)
For https://github.com/geoarrow/geoarrow-rs/pull/1024
=> Add functions to change coordinate type of a geometry array

rust/geoarrow-array/src/array/wkb.rs, rust/geoarrow-array/src/builder/mod.rs, rust/geoarrow-array/src/builder/wkb.rs, rust/geoarrow-array/src/capacity/mod.rs, rust/geoarrow-array/src/capacity/wkb.rs, rust/geoarrow-array/src/cast.rs, rust/geoarrow-array/src/datatypes.rs
Follow up from https://github.com/geoarrow/geoarrow-rs/pull/1032, where I missed `WKBCapacity` -> `WkbCapacity` and `WKBBuilder` -> `WkbBuilder`.
Also cleans up docstrings in the `GeoArrowType` enum.
=> Finish title-casing WKB-related concepts

Cargo.lock, Cargo.toml, python/geoarrow-core/python/geoarrow/rust/core/enums.py, rust/geoarrow-array/src/crs.rs, rust/geoarrow-array/src/lib.rs, rust/pyo3-geoarrow/Cargo.toml, rust/pyo3-geoarrow/src/array.rs, rust/pyo3-geoarrow/src/chunked_array.rs, rust/pyo3-geoarrow/src/coord_buffer.rs, rust/pyo3-geoarrow/src/coord_type.rs, rust/pyo3-geoarrow/src/crs.rs, rust/pyo3-geoarrow/src/data_type.rs, rust/pyo3-geoarrow/src/dimension.rs, rust/pyo3-geoarrow/src/error.rs, rust/pyo3-geoarrow/src/ffi/from_python/mod.rs, rust/pyo3-geoarrow/src/ffi/from_python/scalar.rs, rust/pyo3-geoarrow/src/ffi/mod.rs, rust/pyo3-geoarrow/src/lib.rs, rust/pyo3-geoarrow/src/offset_buffer.rs, rust/pyo3-geoarrow/src/scalar.rs
- Add `rust/pyo3-geoarrow` directory and module
- This can be a module in the main `rust` monorepo crates, because it doesn't rely on the Python interpreter at all; it just relies on the `pyo3` dependency.
- `GeoArrowArray` is the Python-facing array type that stores all geometry array types, including WKB and WKT arrays
- `GeoArrowType` stores extension type information and metadata.
=> Update existing pyo3-geoarrow code and move to `rust/pyo3-geoarrow`

python/geoarrow-io/src/io/parquet/sync.rs
Happy to add similar provisions (as a struct or kwargs) to the `ParquetWriter` class.
=> parquet writer properties for compression, writer version

Cargo.lock, Cargo.toml, rust/geodatafusion/Cargo.toml, rust/geodatafusion/src/data_types.rs, rust/geodatafusion/src/error.rs, rust/geodatafusion/src/lib.rs, rust/geodatafusion/src/udf/geos/mod.rs, rust/geodatafusion/src/udf/mod.rs, rust/geodatafusion/src/udf/native/accessors/coord_dim.rs, rust/geodatafusion/src/udf/native/bounding_box/box_2d.rs, rust/geodatafusion/src/udf/native/bounding_box/expand.rs, rust/geodatafusion/src/udf/native/constructors/point.rs, rust/geodatafusion/src/udf/native/io/geohash.rs, rust/geodatafusion/src/udf/native/io/wkb.rs, rust/geodatafusion/src/udf/native/io/wkt.rs, rust/geodatafusion/src/udf/native/processing/concave_hull.rs, rust/geodatafusion/src/udf/native/processing/simplify.rs, rust/geodatafusion/src/udf/native/processing/simplify_preserve_topology.rs, rust/geodatafusion/src/udf/native/processing/simplify_vw.rs
- Pins to the v47 release candidate git rev of datafusion upstream, in order to unblock testing since we need datafusion to rely on Arrow 55 and object_store 0.12.
- Fixes some imports to read from new locations
- These updates are worthwhile, and so I don't want to throw them away, but I think we should wait on putting more effort into the geoarrow-datafusion integration until the core `geoarrow` is more stable and hopefully upstream supports extension types better.
=> Small clean ups to geodatafusion crate

rust/geoarrow-array/src/scalar/polygon.rs
Previously got a panic:
```
thread 'scalar::polygon::test::test_access_empty_polygon' panicked at rust/geoarrow-array/src/scalar/polygon.rs:74:9:
attempt to subtract with overflow
```
In the case of an empty polygon, `start` == `end`. Only a non-empty polygon has a valid number of interiors.
=> Fix accessing empty polygon through geo-traits

rust/geoarrow-array/src/array/linestring.rs, rust/geoarrow-array/src/array/multilinestring.rs, rust/geoarrow-array/src/array/multipoint.rs, rust/geoarrow-array/src/array/multipolygon.rs, rust/geoarrow-array/src/array/polygon.rs
Note that we can't do this test with any array that has an empty point, because `geo`/`geo-types` don't support empty points.
=> Add `geo` round trip tests with null and empty geometries

rust/geoarrow-array/src/array/geometry.rs, rust/geoarrow-array/src/builder/geometry.rs
Ensures that the null indices are correctly retrieved from a union array (e.g. GeometryArray)
=> GeometryArray: Fix offsets when pushing null

rust/geoarrow-array/src/array/geometry.rs, rust/geoarrow-array/src/array/geometrycollection.rs, rust/geoarrow-array/src/array/linestring.rs, rust/geoarrow-array/src/array/mixed.rs, rust/geoarrow-array/src/array/multilinestring.rs, rust/geoarrow-array/src/array/multipoint.rs, rust/geoarrow-array/src/array/multipolygon.rs, rust/geoarrow-array/src/array/point.rs, rust/geoarrow-array/src/array/polygon.rs, rust/geoarrow-array/src/array/rect.rs, rust/geoarrow-array/src/array/wkb.rs, rust/geoarrow-array/src/array/wkt.rs, rust/geoarrow-array/src/builder/geometry.rs, rust/geoarrow-array/src/builder/geometrycollection.rs, rust/geoarrow-array/src/builder/mixed.rs, rust/geoarrow-array/src/capacity/geometrycollection.rs, rust/geoarrow-array/src/capacity/mixed.rs, rust/geoarrow-array/src/cast.rs, rust/geoarrow-array/src/trait_.rs
- Partly a legacy holdover but we have a "MixedArray" concept. This is now used only as the child of a `GeometryCollectionArray`. So a `GeometryCollectionArray` holds an offset buffer + a Mixed array. This means that the `MixedArray` itself will **never** need to be concerned with null input. Because the `GeometryCollectionArray` will always itself handle null input before it reaches the `MixedArray`. This means we can simplify a lot of the `MixedArrayBuilder` APIs to only take in non-null geometries.
- Modify `GeoArrowArray` trait to have `logical_nulls` but not `nulls`. The upstream `Array` trait has a weird separation between [`nulls`](https://docs.rs/arrow/latest/arrow/array/trait.Array.html#tymethod.nulls) and [`logical_nulls`](https://docs.rs/arrow/latest/arrow/array/trait.Array.html …
=> Improved null handling for `GeometryArray`

rust/geoarrow-array/src/array/geometry.rs, rust/geoarrow-array/src/array/geometrycollection.rs, rust/geoarrow-array/src/array/linestring.rs, rust/geoarrow-array/src/array/multilinestring.rs, rust/geoarrow-array/src/array/multipoint.rs, rust/geoarrow-array/src/array/multipolygon.rs, rust/geoarrow-array/src/array/point.rs, rust/geoarrow-array/src/array/polygon.rs, rust/geoarrow-array/src/array/rect.rs, rust/geoarrow-array/src/array/wkb.rs, rust/geoarrow-array/src/array/wkt.rs, rust/geoarrow-array/src/builder/geometry.rs, rust/geoarrow-array/src/trait_.rs, rust/pyo3-geoarrow/src/array.rs, rust/pyo3-geoarrow/src/chunked_array.rs
- Fix deferred null application in geometry builder. The `GeometryBuilder` has an (internal) concept of "deferred nulls". That is, before a valid geometry has been pushed, we don't know where to push a null value. Ideally we want to push a null value to the same array as future valid geometries, so that it's easier to "downcast" to a single concrete array type if desired. 
- Previously the deferred nulls were broken because we were pushing the nulls to the children but not updating the `types` and `offsets` in the top-level union array.
- Add a test where all nulls and no valid geometries are pushed. 
- Add a test where partial nulls are pushed.
=> Fix deferred null handling in `GeometryBuilder`

rust/geoarrow-array/src/array/mixed.rs, rust/geoarrow-array/src/array/wkt.rs, rust/geoarrow-array/src/cast.rs, rust/geoarrow-geoparquet/src/writer/encode.rs, rust/geodatafusion/src/udf/native/io/wkt.rs
- New `to_wkb`, `to_wkt`, `from_wkb`, `from_wkt`.
- I really don't like the `prefer_multi` parameter in `from_wkb` and `from_wkt` but not sure what to do about it.
- Added tests.
- ~~Skipped `GeometryArray` tests because it looks like we might have some general nullability issues in the `GeometryArray` implementation that I want to look into separately.~~ [`d7680de` (#1070)](https://github.com/geoarrow/geoarrow-rs/pull/1070/commits/d7680deb362c1b58ebd7eb40a8167ca51bc075a8) restored these tests, thanks to fixes in #1071
=> Add `geoarrow_array::cast::to_wkb`, `to_wkt` ,`from_wkb`, `from_wkt`

rust/geoarrow-array/src/array/coord/combined.rs, rust/geoarrow-array/src/array/coord/interleaved.rs, rust/geoarrow-array/src/array/coord/separated.rs, rust/geoarrow-array/src/builder/coord/combined.rs, rust/geoarrow-array/src/builder/coord/interleaved.rs, rust/geoarrow-array/src/builder/coord/separated.rs, rust/geoarrow-array/src/builder/geometrycollection.rs, rust/geoarrow-array/src/builder/linestring.rs, rust/geoarrow-array/src/builder/mixed.rs, rust/geoarrow-array/src/builder/multilinestring.rs, rust/geoarrow-array/src/builder/multipoint.rs, rust/geoarrow-array/src/builder/multipolygon.rs, rust/geoarrow-array/src/builder/offsets.rs, rust/geoarrow-array/src/builder/point.rs, rust/geoarrow-array/src/builder/polygon.rs, rust/geoarrow-array/src/builder/rect.rs, rust/geoarrow-array/src/geozero/import/linestring.rs, rust/geoarrow-array/src/geozero/import/multilinestring.rs, rust/geoarrow-array/src/geozero/import/multipoint.rs, rust/geoarrow-array/src/geozero/import/multipolygon.rs, rust/geoarrow-array/src/geozero/import/polygon.rs
- Remove `From` for converting a builder to a buffer; always use `finish`
- Add parameter for default value in `initialize`
- Remove from public API: `CoordBuffer::push_nan_coord`, `CoordBuffer::push_point`, 
- Make low-level builder APIs `push_coord`, `try_push_usize`, `try_push_geom_offset`, etc, `pub(crate)`. I think these are only used by the geozero builders.
- Remove unused methods from `OffsetBuilder`
-
=> Remove unnecessary builder APIs from public API

rust/geoarrow-array/src/builder/geometry.rs, rust/geoarrow-array/src/capacity/geometry.rs, rust/geoarrow-array/src/capacity/geometrycollection.rs, rust/geoarrow-array/src/capacity/mixed.rs, rust/geoarrow-array/src/capacity/point.rs, rust/geoarrow-array/src/capacity/wkb.rs
- Rename `gcs` to `geometry_collections` in `GeometryCapacity`
- Remove `from_owned_geometries` (it's easy to map over an iterator to take a reference)
- Remove unused mixed capacity methods
-
=> Remove unused capacity APIs

rust/geoarrow-array/src/array/geometry.rs, rust/geoarrow-array/src/array/geometrycollection.rs, rust/geoarrow-array/src/builder/geometry.rs, rust/geoarrow-array/src/builder/geometrycollection.rs, rust/geoarrow-array/src/builder/mixed.rs, rust/geoarrow-array/src/capacity/geometry.rs, rust/geoarrow-array/src/cast.rs, rust/geoarrow-array/src/datatypes.rs, rust/geoarrow-array/src/geozero/import/geometry.rs, rust/geoarrow-array/src/test/geometry.rs, rust/geoarrow-array/src/test/geometrycollection.rs, rust/geoarrow-cast/src/cast.rs, rust/geoarrow-geoparquet/src/reader/parse.rs, rust/geoarrow-geoparquet/src/test/geoarrow_data/example.rs, rust/geoarrow-geos/src/import/array/geometry.rs, rust/geoarrow-geos/src/import/array/geometrycollection.rs
Closes https://github.com/geoarrow/geoarrow-rs/issues/1075.
Ref https://github.com/stac-utils/rustac/pull/708#discussion_r2052669060, cc @gadomski 
- Removes `prefer_multi` as part of the primary constructors, always defaulting to `false`, and then adds a `with_prefer_multi` after the constructor.
=> Default `prefer_multi` to `false` and require explicit opt-in

rust/geoarrow-geoparquet/src/test/geoarrow_data/example.rs, rust/geoarrow-geoparquet/src/test/geoarrow_data/example_crs.rs, rust/geoarrow-geoparquet/src/test/geoarrow_data/mod.rs, rust/geoarrow-geoparquet/src/test/mod.rs
Tests that the files in https://github.com/geoarrow/geoarrow-data/tree/3feaaa0b56758e2b5d7afc1c44c6555cb589d295/example-crs/files can be read and that the parsed CRS in the GeoArrow metadata matches the literal PROJJSON saved in those files (which I extracted using pyarrow)
=> Add GeoParquet CRS tests for reading data

Cargo.lock, Cargo.toml, rust/geoarrow-array/src/array/geometry.rs, rust/geoarrow-array/src/array/geometrycollection.rs, rust/geoarrow-array/src/array/linestring.rs, rust/geoarrow-array/src/array/mixed.rs, rust/geoarrow-array/src/array/multilinestring.rs, rust/geoarrow-array/src/array/multipoint.rs, rust/geoarrow-array/src/array/multipolygon.rs, rust/geoarrow-array/src/array/point.rs, rust/geoarrow-array/src/array/polygon.rs, rust/geoarrow-array/src/array/rect.rs, rust/geoarrow-array/src/array/wkb.rs, rust/geoarrow-array/src/array/wkt.rs, rust/geoarrow-array/src/builder/geometrycollection.rs, rust/geoarrow-array/src/builder/mixed.rs, rust/geoarrow-array/src/trait_.rs, rust/geodatafusion/Cargo.toml, rust/geodatafusion/src/data_types.rs, rust/geodatafusion/src/lib.rs, rust/geodatafusion/src/udf/native/io/mod.rs, rust/geodatafusion/src/udf/native/io/wkb.rs, rust/geodatafusion/src/udf/native/mod.rs
Working `ST_AsBinary` even persisting CRS!
Enabled by https://github.com/apache/datafusion/pull/15646
- Restore `geodatafusion` crate and restore `datafusion` dependency (pinned to upstream main)
- Add `with_metadata` to all concrete arrays and to the `GeoArrowArray` trait so that we can replace the metadata (e.g. CRS) of an existing array.
- Remove `metadata` field from `MixedGeometryArray` because the inner array of the GeometryCollectionArray doesn't need to store GeoArrow metadata.
=> DataFusion extension types working proof of concept!

README.md
ref https://github.com/geoarrow/geoarrow-rs/issues/1095
cc @BlakeOrth
=> Update top-level readme with project status and refactoring note

rust/geoarrow-array/src/array/wkb.rs, rust/geoarrow-array/src/array/wkt.rs, rust/geoarrow-array/src/datatypes.rs, rust/geoarrow-geoparquet/src/writer/metadata.rs, rust/geoarrow-schema/src/type.rs, rust/geoarrow/src/array/binary/array.rs, rust/geoarrow/src/array/wkt/array.rs, rust/geoarrow/src/datatypes.rs, rust/geodatafusion/src/udf/native/io/wkb.rs
- Allow `BinaryView` in `WkbType::supports_data_type` and allow `Utf8View` in `WkbType::supports_data_type`
- Remove `WkbType::data_type` and `WktType::data_type` because the geoarrow type concepts are no longer easily associated with a single `DataType`. (Previously, we had a `large: bool` parameter that determined whether `LargeBinary` or `Binary` would be generated as the `DataType`)
- Remove `to_field` from `WkbType` and `WktType` since it's just a wrapper around `with_extension_type`
=> Allow Arrow binary view and string view types for `WkbType` and `WktType` in `geoarrow-schema`

rust/geoarrow-array/src/array/wkb.rs, rust/geoarrow-array/src/array/wkt.rs, rust/geoarrow-schema/src/type.rs
We should be able to construct a `WkbArray` or `WktArray` from a binary/string array that doesn't have any existing geospatial metadata on the `Field`.
- Add `Default` to `WktArray` and `WkbArray` (since there's no need to choose coord type)
- Define a default wkt/wkb type (with empty CRS) if no geoarrow metadata exists already on the field.
- Adds tests
=> Allow missing GeoArrow metadata in WktArray::try_from and WkbArray::try_from

rust/geoarrow-array/src/array/mod.rs, rust/geoarrow-array/src/array/wkb.rs, rust/geoarrow-array/src/array/wkb_view.rs, rust/geoarrow-array/src/array/wkt.rs, rust/geoarrow-array/src/array/wkt_view.rs, rust/geoarrow-array/src/cast.rs, rust/geoarrow-array/src/datatypes.rs, rust/geoarrow-array/src/geozero/export/data_source/mod.rs, rust/geoarrow-cast/src/downcast.rs, rust/geoarrow-flatgeobuf/src/writer.rs, rust/geoarrow-geoparquet/src/total_bounds.rs, rust/geoarrow-geoparquet/src/writer/metadata.rs
Now that we support view types as part of the upcoming 0.2 spec release: https://github.com/geoarrow/geoarrow/pull/84
- Add `WkbViewArray` and `WktViewArray` wrapping the underlying Arrow view array types.
- Add `WkbView` and `WktView` to `GeoArrowType` enum.
- Add `as_wkb_view` and `as_wkt_view` to `AsGeoArrowArray` trait.
- Add `WkbArrayType` and `WktArrayType` traits to abstract each of the concrete wkb/wkt array types
- Implement From between WKB and WKT array types
Closes #1081, closes #942.
=> Add `WkbViewArray` and `WktViewArray`

rust/geoarrow-array/src/array/wkb.rs, rust/geoarrow-array/src/builder/geometry.rs, rust/geoarrow-array/src/builder/geometrycollection.rs, rust/geoarrow-array/src/builder/wkb.rs, rust/geoarrow-array/src/datatypes.rs
With geo-traits 0.3, all geometries _must_ also implement `GeometryTrait`. Therefore, when the overhead of going through `geo_traits::GeometryTrait` is small enough and when going through `push_geometry` is infallible, we might as well clean up the builder interface by only exposing a `push_geometry` instead of also all the other `push*` functions.
Closes https://github.com/geoarrow/geoarrow-rs/issues/1113
=> Reduce public API surface of WkbBuilder, GeometryBuilder, and GeometryCollectionBuilder

rust/geoarrow-array/src/builder/geometry.rs, rust/geoarrow-array/src/builder/geometrycollection.rs, rust/geoarrow-array/src/builder/linestring.rs, rust/geoarrow-array/src/builder/mixed.rs, rust/geoarrow-array/src/builder/multilinestring.rs, rust/geoarrow-array/src/builder/multipoint.rs, rust/geoarrow-array/src/builder/multipolygon.rs, rust/geoarrow-array/src/builder/point.rs, rust/geoarrow-array/src/builder/polygon.rs, rust/geoarrow-array/src/geozero/import/geometry.rs, rust/geoarrow-array/src/trait_.rs
The term `Geometry` should only be used for the concrete geometry type `Geometry`.
Any generic trait should be prefixed with `GeoArrow`
Closes https://github.com/geoarrow/geoarrow-rs/issues/1119
=> Rename `GeometryArrayBuilder` to `GeoArrowArrayBuilder`

rust/geoarrow-array/src/builder/geometry.rs, rust/geoarrow-array/src/builder/geometrycollection.rs, rust/geoarrow-array/src/builder/linestring.rs, rust/geoarrow-array/src/builder/multilinestring.rs, rust/geoarrow-array/src/builder/multipoint.rs, rust/geoarrow-array/src/builder/multipolygon.rs, rust/geoarrow-array/src/builder/point.rs, rust/geoarrow-array/src/builder/polygon.rs, rust/geoarrow-array/src/geozero/import/geometry.rs, rust/geoarrow-array/src/trait_.rs
Note that adding `push_geometry` causes this trait to no longer be dyn-compatible, because there's a generic for `GeometryTrait` in `push_geometry`.
This is not yet exported publicly so that we can iterate on the design, and in particular decide whether we need dyn-compatibility or not. Hopefully when we implement more format parsers it'll be more clear.
Closes https://github.com/geoarrow/geoarrow-rs/issues/1118
=> Add `push_geometry` method to `GeoArrowArrayBuilder` trait

.github/workflows/ci.yml, Cargo.lock, Cargo.toml
We're not yet removing all code, but at least removing `geoarrow` from the top-level cargo workspace, so that we can upgrade versions like `geo-traits`.
=> Remove geoarrow crate from workspace

rust/geoarrow-array/src/array/coord/combined.rs, rust/geoarrow-array/src/array/coord/interleaved.rs, rust/geoarrow-array/src/array/linestring.rs, rust/geoarrow-array/src/array/multipoint.rs, rust/geoarrow-array/src/array/multipolygon.rs, rust/geoarrow-array/src/capacity/mod.rs, rust/geoarrow-array/src/capacity/multipoint.rs, rust/geoarrow-array/src/util.rs, rust/geodatafusion/src/udf/native/measurement/area.rs
- Reduce dead code
- Remove remaining `into_inner` methods on arrays (closes https://github.com/geoarrow/geoarrow-rs/issues/1111)
- Remove `PointCapacity` from public API.
=> Reduce dead code in geoarrow-array

.github/workflows/conventional-commits.yml
Trying to enforce that PRs use conventional commits so that we can use tools like `cargo changelog` and `cargo smart-release` to help with releases.
=> ci: Verify that PR titles follow conventional commits

rust/geoarrow-schema/src/datatype.rs, rust/geoarrow-schema/src/type.rs
- GeoArrow metadata can be somewhat sizeable, at least when a large PROJJSON string is contained within it. Because of this, storing the `Metadata` under an `Arc` makes sense so that cloning the type is very cheap.
We had already been storing `Arc<Metadata>` inside of the GeoArrow extension types, but we had been defining the associated type on `ExtensionType` as `Metadata`. That means that whenever someone accessed `ExtensionType::metadata` they would get a `&Metadata` instead of a `&Arc<Metadata>`. The former is more expensive to clone than the latter, and you would need to put it into a _new_ `Arc`. Now it's possible to just clone the existing `Arc`.
=> feat: Define `Arc<Metadata>` as the associated type for `ExtensionType`

rust/geoarrow-schema/src/coord_type.rs, rust/geoarrow-schema/src/type.rs
Pending https://github.com/geoarrow/geoarrow/pull/88, cc @paleolimbot
=> feat(geoarrow-schema): Set `CoordType::Separated` as default

python/geoarrow-core/python/geoarrow/rust/core/_data_type.pyi, python/geoarrow-core/python/geoarrow/rust/core/_rust.pyi, python/geoarrow-core/src/lib.rs, python/pyproject.toml, python/tests/core/test_geoarrow_type.py, python/uv.lock, rust/pyo3-geoarrow/src/array.rs, rust/pyo3-geoarrow/src/array_reader.rs, rust/pyo3-geoarrow/src/chunked_array.rs, rust/pyo3-geoarrow/src/data_type.rs, rust/pyo3-geoarrow/src/lib.rs
- Add `large_wkb`, `wkb_view`, `large_wkt`, `wkt_view` constructors.
- Add tests for interop with pyarrow and geoarrow-types.
- Improved documentation
- Remove required coordinate type argument, defaulting to separated coord type.
- Improved repr that doesn't show the raw arrow-rs Field display
For https://github.com/geoarrow/geoarrow-rs/issues/1175
=> feat(python): Stabilize GeoArrowType object

rust/geoarrow-array/src/lib.rs, rust/geoarrow-array/src/trait_.rs
This parallels https://docs.rs/pyo3-arrow/latest/pyo3_arrow/ffi/trait.ArrayReader.html and https://docs.rs/pyo3-arrow/latest/pyo3_arrow/ffi/struct.ArrayIterator.html.
It's quite useful to have an iterator of GeoArrow arrays with a known geometry type in advance.
=> feat(geoarrow-array): Add `GeoArrowArrayReader` trait and `GeoArrowArrayIterator` struct

rust/pyo3-geoarrow/src/array_reader.rs, rust/pyo3-geoarrow/src/chunked_array.rs, rust/pyo3-geoarrow/src/input.rs
- Hold `Box<dyn GeoArrowArrayReader>` directly inside the `PyGeoArrayReader`
- Implement conversions between `Box<dyn GeoArrowArrayReader>` and `Box<dyn ArrayReader>`
- Validation when constructing a new `PyGeoChunkedArray` that all arrays have the same GeoArrowType.
=> chore(python): Refactor to use upstream GeoArrowArrayReader trait

Cargo.lock, Cargo.toml
Bumped Datafusion to 48.
No changes in code were necessary, as extension types were already used.
=> chore: Bump Datafusion to 48

rust/geoparquet/src/writer/encode.rs
It's weird but I got
```
Compiling geoparquet v0.4.0 (/Users/kyle/github/geoarrow/geoarrow-rs/target/package/geoparquet-0.4.0)
error[E0277]: the trait bound `Arc<dyn GeoArrowArray>: GeoArrowArray` is not satisfied
--> src/writer/encode.rs:104:42
|
104 |             let covering = bounding_rect(&from_arrow_array(array, field)?)?;
|                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `GeoArrowArray` is not implemented for `Arc<dyn GeoArrowArray>`
|
= help: the following other types implement trait `GeoArrowArray`:
GenericWkbArray<O>
GenericWktArray<O>
GeometryArray
GeometryCollectionArray
LineStringArray
MultiLineStringArray
MultiPointArray
MultiPolygonArray
and 5 others
= note: required for the cast from `&Arc<dyn GeoArrowArray>` to `&dyn GeoArrowArray`
For …
```
=> fix(geoparquet): Fix crate publish for 0.4

Cargo.lock, rust/geodatafusion/Cargo.toml, rust/geodatafusion/src/udf/geo/mod.rs, rust/geodatafusion/src/udf/geo/relationships/mod.rs, rust/geodatafusion/src/udf/geo/relationships/topological/intersects.rs, rust/geodatafusion/src/udf/geo/relationships/topological/mod.rs, rust/geodatafusion/src/udf/mod.rs
I'm finally connecting the whole DataFusion stack together and it's so fulfilling.
These two screenshots are from:
```sql
SELECT ST_Intersects(ST_GeomFromText('LINESTRING ( 0 0, 0 2 )'), geometry) FROM t;
```
(where geometry is an array with POINT(0.0 0.0) and POINT(2.0 2.0)).
And
```sql
SELECT ST_Intersects(ST_GeomFromText('POINT(0 0)'), ST_GeomFromText('LINESTRING ( 0 0, 0 2 )'));
```
This also uses geo's `PreparedGeometry` automatically when one of the sides is a scalar and the other is an array
=> feat(geodatafusion): Add `ST_Intersects`

rust/geoarrow-geo/src/contains.rs, rust/geoarrow-geo/src/lib.rs
Addresses #1205 , Follows #1207 example for DE-9IM predicates  and added `contains`. Used [geo's](https://docs.rs/geo/latest/geo/algorithm/contains/trait.Contains.html) `contain` method. 
Tests right now are right polygon contained in left, two polygons that don't contain one another, and mixed geometry of line and point being contained in line.
Please let me know if more tests should be added.
=> feat: contains fn 

rust/geodatafusion/src/udf/native/io/wkb.rs
`ST_GeomFromWKB` currently only works with a subset of the standard binary types. Most users on the latest DataFusion release probably won't have an issue with this today, but I'm currently using the `main` branch of DataFusion for several reasons and this defaults to using the view types (`BinaryView`, `Utf8View`, etc.) instead of `Binary`, `Utf8`, and so on.
This PR adds support for loading WKB geometries from a `BinaryView` column, which is how geoparquet geometry fields seem to be interpreted by default in the upcoming release.
=> feat(geodatafusion): Allow loading WKB from BinaryView columns

Cargo.lock, Cargo.toml, rust/geoarrow-geo/src/area.rs, rust/geoarrow-geo/src/centroid.rs, rust/geoarrow-geo/src/contains.rs, rust/geoarrow-geo/src/convex_hull.rs, rust/geoarrow-geo/src/intersects.rs, rust/geoarrow-geo/src/lib.rs, rust/geoarrow-geo/src/relate.rs, rust/geoarrow-geo/src/util/mod.rs, rust/geoarrow-geo/src/util/to_geo.rs, rust/geodatafusion/src/udf/geo/relationships/topological/intersects.rs, rust/geodatafusion/src/udf/geo/relationships/topological/relate.rs
@ianthetechie brought up in https://github.com/geoarrow/geoarrow-rs/discussions/1238 that geoarrow-geo no longer compiled on latest Rust stable on main. I'd forgotten that in the original `geoarrow` code I overrode how to convert how to convert to `geo` objects. There's something about trait objects that causes the compilation failure. Pure functions are fine to use recursion in this way.
Closes https://github.com/geoarrow/geoarrow-rs/issues/1240
=> fix(geoarrow-geo): Fix compilation error when converting geo-traits to `geo` geometries

Cargo.lock, Cargo.toml, rust/geodatafusion/src/error.rs
Title says it all. New version just dropped, and as far as I can tell there's only one small API change that immediately affected geodatafusion.
=> chore(geodatafusion): Upgrade to DataFusion 49.0.0

Cargo.lock, rust/geoarrow-flatgeobuf/Cargo.toml, rust/geoarrow-flatgeobuf/src/lib.rs, rust/geoarrow-flatgeobuf/src/reader/async.rs, rust/geoarrow-flatgeobuf/src/reader/common.rs, rust/geoarrow-flatgeobuf/src/reader/mod.rs, rust/geoarrow-flatgeobuf/src/reader/object_store.rs, rust/geoarrow-flatgeobuf/src/reader/schema.rs, rust/geoarrow-flatgeobuf/src/reader/sync.rs, rust/geoarrow-flatgeobuf/src/writer.rs, rust/geodatafusion-flatgeobuf/src/file_format.rs
- Add schema scanner for inferring schema from dataset without known schema in header
- Require crate-wide docs
- Add HeaderInfo struct with full information from FlatGeobuf header
- Cleaner API for enabling schema inference. Right now, our public APIs have users pass in a bare FeatureIter, but if the schema isn't known, we have to exhaust the iterator just to infer the schema.
=> feat(geoarrow-flatgeobuf): Improved schema inference & expose more from header

rust/geoarrow-array/src/array/wkb.rs, rust/geoarrow-array/src/builder/wkb.rs, rust/geoarrow-array/src/cast.rs, rust/geoarrow-geos/src/import/array/wkb.rs
- Currently the WkbBuilder uses `unwrap` when adding geometries to the builder. This should not panic.
=> fix(geoarrow-array)!: WkbBuilder should return result when appending geometries

Cargo.lock, Cargo.toml
I had been using the `alamb` source to test with https://github.com/apache/datafusion/pull/16690
=> chore(geodatafusion): Use datafusion git pin on main to support Arrow 56

rust/geodatafusion/README.md, rust/geodatafusion/src/data_types.rs, rust/geodatafusion/src/udf/native/io/wkb.rs, rust/geodatafusion/src/udf/native/io/wkt.rs
- Add `st_wkbtosql` as alias of `ST_GeomFromWKB`
- Add `st_geometryfromtext`, `st_wkttosql` as aliases of `ST_GeomFromText`
- Remove unused code
- Remove items from function reference table that use curves
=> feat(geodatafusion): Add aliases for WKT and WKB functions

Cargo.lock, Cargo.toml, rust/geodatafusion-geojson/Cargo.toml, rust/geodatafusion-geojson/src/file_format.rs, rust/geodatafusion-geojson/src/lib.rs
- New `geodatafusion-geojson` crate with GeoJSON table provider.
- Currently this table provider only supports writing, not reading.
=> feat(geodatafusion-geojson): Add GeoJSON table provider to write to line-delimited GeoJSON

Cargo.lock, rust/geoarrow-array/CHANGELOG.md, rust/geoarrow-array/src/cast.rs
Avoid actually materializing `geoms` unless needed.
=> perf(geoarrow-array): Improve perf of `from_wkb`/`from_wkt` when parsing to WKB/WKT output types

.github/workflows/python-core-wheels.yml, .github/workflows/python-io-wheels.yml, python/CHANGELOG.md
To fix the broken python wheel build: https://github.com/geoarrow/geoarrow-rs/actions/runs/17688206370/job/50277114526
=> ci(Python): Remove Windows x86 build

python/CHANGELOG.md, python/Cargo.lock, python/Cargo.toml
Update the lockfile to be able to build in release mode #1339
=> chore: Prepare Python 0.5.3 release

python/mkdocs.yml
`mkdocs` warns about a couple more files that are built but not included in the "nav" configuration:
- api/compute/enums.md
- api/compute/functions.md
- api/compute/types.md
- api/core/geometry/type.md
- api/io/gdal.md
- ecosystem/geopandas.md
=> docs: include constructor docs in the table of contents
